export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'title-language': 'Language',
  'label-generic-hello': 'Hello, ',

  'title-profiles': 'Profiles',
  'title-users': 'Users',
  'title-documents': 'Documents',
  'title-work-instruction': 'Work Instruction',
  'WORK_INSTRUCTION_PROCESS': 'Instrução de trabalho Process',
  'WORK_INSTRUCTION_QUALITY': 'Instrução de trabalho Quality',
  'CREATE_NEW_WORK_INSTRUCTION': 'Create new Work Instructions',
  'title-work-instruction-and-model': 'Work Instruction and Model',
  'title-tools': 'Tools',
  'title-models': 'Models',
  'title-materials': 'Materials',
  'title-ipe': 'IPE\'s and ESD\'s',
  'title-products': 'Products',
  'title-process-flow': 'Process Flow',
  'title-process-phase': 'Process Phase',
  'title-production-line': 'Production Line',
  'title-trainings': 'Training',
  'title-evaluation': 'Evaluation',
  'title-performance-panel': 'Performance Panel',
  'title-tracking-panel': 'Tracking Panel',
  'title-resource-allocation': 'Resource Allocation',
  'title-biometry': 'Biometry',
  'trainings-tips': 'Results of the evaluations',

  'title-quality-notes': 'Quality Notes',
  'title-waste-generation': 'Waste Generation',
  'title-general-notes': 'General Notes',
  'title-code': 'Code',
  'label-flow-project-add': 'Project name',
  'label-flow-code-add': 'Project Code',
  'label-flow-client-add': 'Client',
  'label-flow-owner-add': 'Owner',
  'label-flow-approval-add': 'Approval',
  'label-flow-flowChart-add': 'Flowchart name',
  'label-flow-status-add': 'Status',
  'title-project': 'Name',
  'title-description': 'Description',
  'title-name': 'Name',
  'title-standard-rpn': 'Standard RPN',
  'title-severity': 'Severity',
  'label-general-instructor': 'Instructor',



  'title-client': 'Client',
  'title-owner': 'Owner',
  'title-approval': 'Approved by',
  'title-flowchart': 'FlowChart',
  'title-last-change': 'Last Change',
  'title-version': 'Version',
  'title-status': 'Status',
  'title-error': 'Error',
  'title-basic-data': 'Basic Data',
  'title-side-nav-configuration': 'Configuration',
  'title-side-nav-configuration-profile': 'Profile Settings',
  'title-step': 'Step',
  'title-tool-add-tool': 'Add Tool',
  'title-model-add-model': 'Add Model',
  'title-process-flow-add-flow': 'Flow Data',
  'title-data-from-it': 'IT Data',
  'title-process-phase-add-process-phase': 'Add Process Phase',
  'title-materials-add-materials': 'Add Materials',
  'title-products-add': 'Add Products',
  'title-ipe-add': 'Add IPE',

  'title-number-posts': 'Qty. Posts',
  'title-number-employee-posts': 'Qty. Employee/Workstation',
  'title-employee': 'Employee',
  'title-workstation': 'Workstation',
  'title-created-at': 'Creation date',
  'title-validity': 'Validity',
  'title-signin': 'Sign In',
  'title-signin-guest': 'Sign In as Guest',
  'title-welcome': 'Welcome',
  'title-signin-biometrics': 'Sign In with Biometry',
  'biometry_is_not_connected': 'Fingerprint is not connected',
  'biometry_cant_be_read': 'Biometry can\'t be read',

  'placeholder-general-description': 'Description',
  'placeholder-general-model': 'Model',

  'placeholder-username': 'Username',
  'placeholder-password': 'Password',
  'placeholder-search-by-name': 'Search by name',
  'placeholder-search-by-profile': 'Search by groups',

  'placeholder-work-instruction-name': 'Instruction Name',
  'placeholder-work-instruction-code': 'Instruction Code',

  'placeholder-work-instruction-stage-process': 'Stage of Process',
  'placeholder-work-instruction-workplace-safety': 'Workplace Safety',
  'placeholder-work-instruction-safety-environmental': 'Environmental Safety',
  'placeholder-work-instruction-impact-reaction-plan': 'Impact Reaction Plan',
  'placeholder-work-instruction-model-code': 'Model Code',
  'placeholder-work-instruction-model-description': 'Model Description',
  'placeholder-work-instruction-material-code': 'Material Code',
  'placeholder-work-instruction-material-description': 'Material Description',
  'placeholder-work-instruction-quality-notes': 'Notes',
  'placeholder-work-instruction-geral-notes': 'Notes',
  'placeholder-image-description': 'Description',

  'placeholder-production-line-leader': 'Production leader',
  'placeholder-production-line-validity': 'Validity',
  'placeholder-production-line-undetermined-validity': 'Undetermined Validity',

  'label-paper': 'Paper',
  'label-plastics': 'Plastics',
  'label-glasses': 'Glasses',
  'label-metals': 'Metals',
  'label-not-recyclable': 'Not Recyclable',
  'label-dangerous-wastes': 'Dangerous Wastes',
  'label-not-generate-waste': 'Does not Generate Waste',
  'label-general-name': 'Name',
  'label-day': 'Day',
  'label-general-list-description': 'Description',
  'label-general-list-model': 'Model',
  'label-general-status': 'Status',
  'label-general-active': 'Active',
  'label-general-inactive': 'Inactive',
  'label-general-initial-date-search': 'Initial Date',
  'label-general-final-date-search': 'Final Date',
  'label-general-undetermined': 'Undetermined',
  'label-general-situation': 'Status',
  'label-general-employee': 'Employee',
  'label-general-employees': 'Employees',
  'label-ipe-description': 'IPE Description',


  'label-work-instruction-materials': 'Materials',
  'label-work-instruction-models': 'Models',
  'label-work-instruction-name': 'Work instruction name',
  'label-work-instruction-search': 'Search work instruction',
  'label-work-instruction-search-by-model': 'Search Work Instruction by Model',
  'label-work-instruction-identification': 'Identification of Work Instruction - I.T.',
  'label-started-workstation': 'Select Workstation Initial',
  'label-work-instruction-ocupational': 'Occupational Safety and Environmental Instruction',
  'label-work-instruction-basic-data-tab': 'Basic Information',
  'label-work-instruction-materials-tools-tab': 'Materials and Tools',
  'label-work-instruction-instructions-tab': 'Work Instructions',
  'label-work-instruction-sesmt-tab': 'SESMT',
  'label-work-instruction-instructions-list-code': 'IT Code',
  'label-workinstruction-view-product': 'IT Name ',
  'label-workinstruction-view-line-station': 'Line/Station',
  'label-workinstruction-view-it-code': 'IT Code',
  'label-workinstruction-view-model-product': 'Model/Product',
  'label-workinstruction-view-approver': 'Approver',
  'label-workinstruction-view-developer': 'Developer',

  'label-work-instruction-list-type-name': 'IT Name',
  'label-work-instruction-list-date': 'Date of homologation',

  'label-tools-search': 'Search tool',
  'label-tool-description': 'Tool Description',

  'label-model-code-search': 'Search Model by Code',
  'label-model-product-search': 'Search Model by Product',
  'label-model-description-search': 'Search Model by Description',
  'label-model-description': 'Model Description',
  'label-model-code': 'Model Code',
  'label-models-and-product': 'Models and Products',

  'label-process-phase-description-search': 'Search Process Phase by Description',
  'label-materials-search': 'Search by Materials',
  'label-code-it-search': 'Search IT Code',
  'label-suggetion-search': 'Search Suggestion',
  'label-all-situation-search': 'All situations',
  'label-result-all': 'All Results',
  'label-ipe-search': 'Search by IPE',
  'label-process-phase-description': 'Process Phase Description',
  'label-materials-description': 'Materials Description',
  'label-products-description': 'Products Description',
  'label-code-description': 'Product Code',

  'label-products-search': 'Search by Products',
  'label-production-line-description-search': 'Search by description',
  'label-production-line-initial-date-search': 'Initial Date',
  'label-production-line-final-date-search': 'Final Date',
  'label-production-line-model-search': 'Search by Model',
  'label-production-line-leader': 'Leader of Production',
  'label-production-line-list-qty-workstation': 'Qty. Workstations',
  'label-line-production-list-validity': 'Validity',

  'placeholder-production-line-qty-workstation': 'Qty. Workstations',

  'label-profile-search': 'Search groups',
  'label-profile-permission': 'Permissions',
  'label-profile-description': 'Profile description',
  'label-profile-visualization': 'Visualization',
  'label-profile-create': 'Create',
  'label-profile-edit': 'Edit',
  'label-profile-delete': 'Delete',

  'label-evaluation-situation-all': 'All status',
  'label-evaluation-situation-avaiable': 'Available',
  'label-evaluation-situation-expired': 'Expired',
  'label-evaluation-situation-planned': 'Planned',
  'label-evaluation-quiz-name': 'Quiz Name',

  'label-flow-status-sketch': 'Sketch',
  'label-flow-status-approval': 'On Approval',
  'label-flow-status-homologation': 'Homologation',
  'label-flow-status-inactive': 'Inactive',


  'label-bt-back': 'Return',
  'label-bt-save-draft': 'Save Draft',
  'label-bt-next': 'Next',
  'label-bt-add-new': 'Add new',
  'label-bt-edit': 'Edit',
  'label-bt-save': 'Save',
  'label-bt-exit-workstation': 'Desallocate',
  'label-bt-cancel': 'Cancel',
  'label-suggestions-it': 'Suggestion',
  'label-suggestions-description-it': 'Description of Suggestion',
  'label-bt-homologation': 'Send to Homologation',
  'label-bt-delete': 'Delete',
  'label-bt-previus': 'Previous',
  'label-bt-finish': 'Finish',
  'label-bt-export': 'Export',
  'label-bt-suggestion': 'Suggestion',
  'BT_OK': 'OK',
  'label-status': 'Status',
  'label-delete': 'Delete',
  'label-duplicate': 'Duplicate',
  'label-edit': 'Edit',
  'label-details': 'Details',
  'label-new': 'New',
  'label-remove': 'Remove',
  'label-confirm-remove': '$description',
  'label-confirm-remove-item': 'Do you want to remove this item?',
  'label-active': 'Active',
  'label-inactive': 'Inactive',
  'label-all': 'All',
  'label-code': 'Code',
  'label-products': 'Products',
  'label-suggestion': 'Suggestion',
  'label-details-suggestion': 'Suggestion Details',
  'label-situation': 'Situation',
  'label-pending': 'Pending',
  'label-closed': 'Closed',
  'label-no-filter': 'No Filter',
  'label-materials': 'Materials',
  'label-description': 'Description',
  'label-description-revision': 'Review Description',

  'label-category': 'Category',
  'label-filter-name': 'Filter by name',
  'label-filter-code': 'Filter by code',
  'label-filter-by': 'Filter by ',
  'label-filter': 'Filter',
  'label-add-filter': 'Add filter',
  'label-active-filters': 'Active filters',
  'label-clear-filters': 'Clear filters',
  'label-type': 'Type',
  'label-image-select': 'Image Select',
  'label-done-register': 'Done register',
  'label-pending-register': 'Pending register',
  'label-identification': 'Identification',
  'label-add': 'Add',
  'label-add-flow': 'Add Flow Data',
  'label-update': 'Update',
  'label-restore': 'Restore',
  'label-key': 'Key',
  'label-value': 'Value',
  'label-serie-number': 'Series number',
  'label-station-type': 'Station type',
  'label-cancel': 'Cancel',
  'label-save': 'Save',
  'label-phase': 'Phase',
  'label-yes': 'Yes',
  'label-no': 'No',
  'label-required': 'Required',
  'label-optional': 'Optional',
  'label-order': 'Order',
  'label-click-drag': 'Click and drag',
  'label-reports': 'Reports',
  'label-register': 'Registration',
  'label-workstation-type-name': 'Description',
  'label-selected-items': 'Selected items',
  'label-available-items': 'Available items',
  'label-no-selected-item': 'No selected item',
  'label-no-available-item': 'No available item',
  'label-review': 'Review',
  'label-start-review' : 'Start Review',
  'label-step': 'Step',
  'label-itens-of-page': 'Items per page',
  'workstation_per_page': 'Workstation per page',
  'label-edit-flowchart': 'Edit flowchart',
  'label-description-it': 'IT Description',
  'label-code-it': 'Code',
  'label-code-it-suggestion': 'Code IT',
  'label-model-it': 'Model',
  'label-place-holder-editor': 'Step Description',
  'label-action-taken': 'Action Taken',
  'label-resolve': 'Resolve',
  'label-version-it': 'Version',

  'label-quantity': 'Qty.',

  'label-resgistration': 'Registration',
  'label-departament': 'Departament',
  'label-last-access': 'Last access',
  'label-assign-profile': 'Assign groups',

  'label-login': 'Login',

  'error-message-connection': 'Connection error.',
  'error-message-not-found': 'Service not found.',
  'message-error-retrieve-product': 'Was not possible to retrieve the product.',
  'message-error-retrieve-bom': 'Was not possible to retrieve the BOM.',
  'message-error-retrieve-product-properties': 'Was not possible to retrieve the product properties.',
  'message-error-retrieve-product-map': 'Was not possible to retrieve the product settings.',
  'message-error-retrieve-production-map': 'Was not possible to retrieve the product production maps.',
  'message-error-retrieve-product-process': 'Was not possible to retrieve the estimated production time.',
  'message-error-delete-product': 'There are records associated with this product.',
  'message-error-delete-product-process': 'There are records associated to this estimated production time.',
  'message-error-delete-workstation-type': 'There are records associated with this workstations type.',
  'message-error-delete-workstation': 'There are records associated with this workstations.',
  'message-error-delete-component': 'There are records associated with this component.',
  'message-error-delete-category': 'There are records associated with this category.',
  'message-error-delete-production-line': 'There are records associated with this production line.',
  'message-error-delete-production-map': 'There are records associated with this production map.',
  'message-error-delete-defect': 'There are records associated with this defect.',
  'message-error-update-item': 'Was not possible to update the item.',
  'message-error-delete': 'Error deleting item.',
  'message-error-value-bigger-than-expect': 'The values must be less than',
  'message-success-insert-item': 'Item has been created.',
  'message-success-update-item': 'Item has been updated.',
  'message-warning-register': 'No records found',


  'already-associated-work-instruction': 'Work Instruction already associated.',

  'label-workstation-code': 'Workstation code',
  'label-workstation-description': 'Workstation description',
  'label-workstation-hostname': 'Workstation hostname',
  'label-production-line-description': 'Description',
  'label-production-line-code': 'Code',
  'label-scrap': 'Scrap',
  'label-goal': 'Goal',
  'label-indicator': 'Indicator',
  'label-scrap-by-period': 'SCRAP_BY_PERIOD',
  'label-username': 'Username',
  'label-profile': 'Profile',
  'label-password': 'Password',
  'label-old-password': 'Old password',
  'label-new-password': 'New password',
  'label-password-confirmation': 'Password confirmation',
  'label-update-settings': 'Update settings',
  'label-name': 'Name',
  'label-cpf': 'CPF',
  'label-admission-date': 'Admission date',
  'label-birth-date': 'Birth date',
  'label-employee-situation': 'Employee Situation',
  'label-leadership-id': 'Lidership ID',
  'label-shift': 'Shift',
  'label-occupation': 'Occupation',


  'label-profile-name': 'Profile name',
  'label-permissions': 'Permissions',
  'label-view': 'View',
  'label-create': 'Create',
  'label-required-fields': 'Required Fields',

  'toast-success-title': 'Success',
  'toast-fail-delete-model-title': 'This model can not be deleted as it is associated with a production line!',
  'toast-attention-title': 'Attention',
  'toast-saved-successfully': 'Item saved successfully',
  'toast-evaluation-not-approved': 'Attention! You do not have the training for this job. Please look for the line leader to provide training',
  'toast-employee-allocated': 'It is necessary to deallocate the employee of the previous post',
  'toast-complete-all-fields': 'Complete all Fields',
  'toast-deleted-successfully': 'Item deleted successfully',
  'toast-updated-successfully': 'Item updated successfully',
  'toast-error-title': 'Error',
  'toast-ipe': 'Type of IPE invalid',
  'toast-error-load': 'Error loading',
  'toast-token-expired': 'Your session has expired',
  'toast-deleted-fmea-error': 'There are registered items',
  'toast-request-review-successfully': 'Review Request sent successfully',
  'folder-not-empty': 'Apenas pastas vazias poderão ser excluídas',
  'toast-select-one-item': 'Select at least one item',
  'toast-deleted-error': 'Error trying delete item.',


  'authentication': 'Authentication',
  'username-or-password-invalids': 'Invalid username or password',
  'user-not-found': 'User not found',
  'month-days': 'Month Days',
  'period-days': 'Period Days',
  'performances': 'Performances',
  'performance': 'Performance',
  'logic': 'Logic',
  'real': 'Real',
  'processes': 'Processes',
  'search': 'Search',
  'month': 'Month',
  'year': 'Year',
  'download-chart': 'Download chart',
  'view-list': 'View in list',
  'msg-chart': 'Click the chart to detail a process',
  'date': 'Date',
  'update-date': 'Update date',
  'serial': 'Serial',
  'process': 'Process',
  'state': 'State',
  'approved': 'Approved',
  'reproved': 'Reproved',
  'repairing': 'In repair',
  'scrap': 'Scraped',
  'terminated': 'Terminated',
  'remove-last-operation': 'Undo last operation',
  'generate-xls': 'Generate XLS file',
  'message-there-are-not-data': 'There\'s no data to show in the chart.',
  'serial-number-not-read': 'No readings for serial number reported.',
  'defects-quantity': 'Defects Quantity',
  'chart-legend': 'Legend',
  'legend-defects': 'Defects Type',
  'start-date': 'Initial Date',
  'end-date': 'Final Date',
  'read': 'Read',
  'binding': 'Binding',
  'read-log': 'Read log',
  'repair-workstation': 'Technical workstations',
  'packing': 'Packing',
  'oqc': 'OQC',
  'defect-record': 'Defect record',
  'panel-management-view': 'Management view panel',
  'change-model': 'Change model',
  'workstation-type-update-success': 'Workstation type updated successfully.',
  'workstation-type-save-success': 'Workstation type saved successfully.',
  'description': 'Description',
  'code': 'Code',
  'category': 'Category',
  'product': 'Product',
  'workstation-update-success': 'Workstation updated successfully.',
  'workstation-save-success': 'Workstation saved successfully.',
  'production-line-save-success': 'Production line saved successfully.',
  'production-line-update-success': 'Production line updated successfully.',
  'next': 'Next',
  'previous': 'Previous',
  'message-warning-inactive-item': 'Would you like to inactive this item ( $workinstruction )?',
  'message-warning-active-item': 'The item will be pendent of homologation. Would you like to continue?',

  'already-exist': 'Item already exist',
  'already-used': 'Item already used',
  'already-selected': 'Item already selected.',
  'cannot-deleted': 'Item cannot be deleted',
  'menu-edit': 'Edit',
  'menu-view': 'Preview',
  'menu-delete': 'Delete',
  'menu-create-preview': 'Create Review',

  'label_module_production_line': 'Production Line',
  'label_module_models': 'Models',
  'label_module_workstation': 'Workstation',
  'label_module_employee': 'Employees',
  'label_module_tools': 'Tools',
  'label_module_process_phases': 'Process Phase',
  'label_module_fmea': 'FMEA',
  'label_module_work_instruction': 'Work Instruction',
  'label_module_process_flow': 'Process Flow',
  'label_module_report': 'Reports',
  'label_module_instruction_visualization': 'Instruction Visualization',
  'label_module_instruction_evaluation': 'Instruction Evaluation',
  'label_module_evaluation_list': 'Evaluation List',
  'label_module_profile_configuration': 'Profile Configuration',

  'label-search-project': 'Search by Name',
  'label-search-code': 'Search by Code',
  'label_module_employee_add': 'Add employee',
  'label-search-employee-departament': 'Search Departament',
  'label-search-employee-profile': 'Search Profile',
  'label_work_station_add': 'Add Workstation',
  'label_work_station_edit': 'Edit Workstation',
  'label-employee-employeedata': 'Employee Data',
  'label-employee-userdata': 'User Data',
  'label-employee-register-biometrics': 'Register Biometrics',
  'label-employee-edit-biometrics': 'Edit Biometry',
  'label-employee-search': 'Search employee',
  'label-import': 'Import',
  'label-import-success': 'Import successfully',
  'label-file-invalid': 'Invalid File',
  'label-import-excel': 'Excel import',


  'label-work-station': 'Workstation',
  'label-search-work-station': 'Search Workstation',

  'label-evaluation-basic-data': 'Basic Data of Evaluations',
  'label-evaluation-questions': 'Evaluation Questions',
  'label-evaluation-general': 'General Feedback',
  'label-evaluation-attempts': 'Number of attempts',
  'label-evaluation-time-over': 'Time is over!',
  'label-evaluation-accomplishment_time': 'Time of accomplishment',
  'label-evaluation-name-quiz': 'Quiz Name',
  'label-evaluation-percent_approval': 'Minimum approval',
  'label-evaluation-feedback_approved': 'Feedback approved',
  'label-evaluation-feedback_disapproved': 'Failed feedback',
  'label_evaluation_add': 'Add Question',
  'label_evaluation_edit': 'Edit Question',
  'label_start': 'Start',
  'label-score': 'Score',

  'label-question-data-question': 'Question data',
  'label-question-name-question': 'Question name',
  'label-question-statement': 'Statement',
  'label-question-multiple': 'Multiple choice',
  'label-question-connect': 'Connect',
  'label-question-complete': 'To complete',
  'label-question-true-false': 'True or False',
  'label-answer': 'Answer',
  'label-true': 'True',
  'label-false': 'False',
  'label_nota': 'Score',
  'msg_aproveed': 'You are approved with ',
  'msg_disapproved': 'You are disapproved with ',
  'label-bt-close-evaluation' : 'Close Test',
  'retake_evaluation': 'Retake Evaluation',
  'TRUE OR FALSE': 'True or False',
  'COMBINE': 'Combine',
  'MULTIPLE CHOICE': 'Multiple Choice',

  'title-resource-allocation-add-employee': 'Add Employee',

  'label-resource-allocation-edit': 'Edit workstations',
  'label-resource-allocation-register': 'Register',
  'label-resource-allocation-relay': 'Relay in',
  'label-resource-allocation-qty-employees': 'Qty. of employees',
  'label-resource-allocation-workstation': 'Workstation',
  'label-resource-allocation-relay-with': 'Relay with',

  'label-performance-panel-realized': 'Realized',
  'label-performance-panel-not-realized': 'Not Realized',
  'label-performance-panel-expired-when': 'Expires on: ',
  'label-performance-panel-expired': 'Expired on: ',
  'label-performance-panel-conclusion-when': 'Conclusion on: ',
  'label-performance-panel-instruction': 'Instruction:',
  'label-performance-panel-score-evaluation': 'Grade',
  'label-performance-panel-evaluation-attempts': 'Attempts',
  'label-performance-panel-production-line-workstation': 'Production Line/Workstation:',
  'label-performance-panel-all': 'All',
  'label-performance-panel-pending': 'Pending',
  'label-performance-panel-done': 'Done',
  'label-performance-panel-records': 'Records',
  'label-performance-panel-record': 'Record',
  'label-performance-panel-none-record': 'Records',
  'label-performance-panel-my-results': 'My Results',
  'label-performance-panel-average': 'Average',
  'label-performance-panel-ranking-by': 'Ranking by',
  'label-performance-panel-workstation': 'Workstation',
  'label-performance-panel-production-line': 'Production Line',
  'label-performance-panel-company': 'Company',
  'label-performance-panel-approbation-in-training': 'In Training',
  'label-performance-panel-approbation-apt': 'Apt',
  'label-performance-panel-approbation-apt-with-observations': 'Apt with observations',
  'label-performance-panel-approbation-inapt': 'Inapt',
  'label-performance-panel-approbation-title': 'Technical Advice',
  'label-approbation-status': 'Status',
  'label-approbation-note': 'Observations',

  'error-title-performance-panel-invalid-trainer': 'Invalid Trainer',
  'error-performance-panel-invalid-trainer': 'You are not allocated as a Trainer.',

  'error-max-alternatives' : 'Quantity of alternatives not allowed. The maximum is 5 alternatives.',
  'error-min-alternatives' : 'Quantity of alternatives not allowed. The minimum is 3 alternatives.',

  'error-max-alternatives-with-photo' : 'You must have at least 1 image and 2 alternatives.',
  'error-not-selected-alternative' : 'You must select an alternate answer.',

  'make_evaluation': 'Make evaluation',
  'invalid_address' : 'Invalid address!',
  'title-evaluation-view-error' : 'Error',
  'bt-dialog-finalize' : 'Finish',
  'bt-dialog-cancel' : 'Cancel',
  'dialog-attention-title': 'Attention!',
  'questions-dialog-evaluation' : 'Do you want to end the test?',
  'subtitle-evaluation' : 'Unanswered questions.',

  'add_logentry': 'Can add log entry' ,
  'change_logentry': 'Can change log entry' ,
  'delete_logentry': 'Can delete log entry' ,
  'add_permission': 'Can add permission' ,
  'change_permission': 'Can change permission' ,
  'delete_permission': 'Can delete permission' ,
  'add_group': 'Can add groups' ,
  'change_group': 'Can change groups' ,
  'delete_group': 'Can delete groups' ,
  'add_contenttype': 'Can add content type' ,
  'change_contenttype': 'Can change content type' ,
  'delete_contenttype': 'Can delete content type' ,
  'add_session': 'Can add session' ,
  'change_session': 'Can change session' ,
  'delete_session': 'Can delete session' ,
  'add_token': 'Can add token' ,
  'change_token': 'Can change token' ,
  'delete_token': 'Can delete token' ,
  'add_user': 'Can add user' ,
  'change_user': 'Can change user' ,
  'delete_user': 'Can delete user' ,
  'add_department': 'Can add department' ,
  'change_department': 'Can change department' ,
  'delete_department': 'Can delete department' ,
  'add_employee': 'Can add employee' ,
  'change_employee': 'Can change employee' ,
  'delete_employee': 'Can delete employee' ,
  'add_evaluation': 'Can add evaluation' ,
  'change_evaluation': 'Can change evaluation' ,
  'delete_evaluation': 'Can delete evaluation' ,
  'add_material': 'Can add material' ,
  'change_material': 'Can change material' ,
  'delete_material': 'Can delete material' ,
  'add_model': 'Can add model' ,
  'change_model': 'Can change model' ,
  'delete_model': 'Can delete model' ,
  'add_module': 'Can add module' ,
  'change_module': 'Can change module' ,
  'delete_module': 'Can delete module' ,
  'add_occupation': 'Can add occupation' ,
  'change_occupation': 'Can change occupation' ,
  'delete_occupation': 'Can delete occupation' ,
  'add_photo': 'Can add photo' ,
  'change_photo': 'Can change photo' ,
  'delete_photo': 'Can delete photo' ,
  'add_processphases': 'Can add process phases' ,
  'change_processphases': 'Can change process phases' ,
  'delete_processphases': 'Can delete process phases' ,
  'add_productionline': 'Can add production line' ,
  'change_productionline': 'Can change production line' ,
  'delete_productionline': 'Can delete production line' ,
  'add_profile': 'Can add groups' ,
  'change_profile': 'Can change groups' ,
  'delete_profile': 'Can delete groups' ,
  'add_profilepermission': 'Can add groups permission' ,
  'change_profilepermission': 'Can change groups permission' ,
  'delete_profilepermission': 'Can delete groups permission' ,
  'add_question': 'Can add question' ,
  'change_question': 'Can change question' ,
  'delete_question': 'Can delete question' ,
  'add_questiontype': 'Can add question type' ,
  'change_questiontype': 'Can change question type' ,
  'delete_questiontype': 'Can delete question type' ,
  'add_resourceallocation': 'Can add resource allocation' ,
  'change_resourceallocation': 'Can change resource allocation' ,
  'delete_resourceallocation': 'Can delete resource allocation' ,
  'add_shift': 'Can add shift' ,
  'change_shift': 'Can change shift' ,
  'delete_shift': 'Can delete shift' ,
  'add_stepinstruction': 'Can add step instruction' ,
  'change_stepinstruction': 'Can change step instruction' ,
  'delete_stepinstruction': 'Can delete step instruction' ,
  'add_tool': 'Can add tool' ,
  'change_tool': 'Can change tool' ,
  'delete_tool': 'Can delete tool' ,
  'add_workinstruction': 'Can add work instruction' ,
  'change_workinstruction': 'Can change work instruction' ,
  'delete_workinstruction': 'Can delete work instruction' ,
  'add_workstation': 'Can add workstations' ,
  'change_workstation': 'Can change workstations' ,
  'delete_workstation': 'Can delete workstations' ,
  'add_alternative': 'Can add alternative' ,
  'change_alternative': 'Can change alternative' ,
  'delete_alternative': 'Can delete alternative' ,
  'add_alternativeanswer': 'Can add alternative answer' ,
  'change_alternativeanswer': 'Can change alternative answer' ,
  'delete_alternativeanswer': 'Can delete alternative answer' ,
  'add_evaluationresult': 'Can add evaluation result' ,
  'change_evaluationresult': 'Can change evaluation result' ,
  'delete_evaluationresult': 'Can delete evaluation result' ,
  'add_questionanswer': 'Can add a question' ,
  'change_questionanswer': 'Can change question answer' ,
  'delete_questionanswer': 'Can delete question answer',
  'title-evaluation-instruction': 'Evaluation Instructions',
  'before you begin' : 'Before you begin',
  'minutes' : 'minutes',
  'no_option_pause' : 'There is no option to pause. Make sure there are no interruptions during the evaluation.',
  'no_close_browser' : 'You can not close your browser during evaluation.',
  'it_before_evaluation': 'It is necessary to see the Working Instructions before the evaluation.',
  'label-bt-it' : 'See Work Instruction',
  'label-bt-evaluation' : 'Perform Evaluation',
  'subtitle-actions' : 'See a working instruction before evaluation.',
  'checkt-it-evaluation' : 'I declare that I have seen the work instruction.',
  'trainings_per_employee': 'Training by Employee',
  'trainings_per_it': 'Employee by work instruction',
  'no-workstations-associated' : 'No workstations associated',
  'label-signature': 'Signature',


  'title_initial_month': 'Initial Month',
  'title_final_month': 'Final Month',
  'title_qtd_partitions': 'Qty. Participants',

  'dashboard_evaluation': 'View Dashboard',
  'dashboard_evaluation_all_employee': 'View All Employees Performance Dashboard',
  'view_question': 'View Question',
  'view_questionanswer': 'View Question Answer',
  'view_questiontype': 'View Question Type',
  'view_alternative': 'View Alternative',
  'view_alternativeanswer': 'View Alternative Answer',
  'view_employee': 'View Employee',
  'view_evaluation': 'View Evaluation',
  'view_evaluationresult': 'View Evaluation Result',
  'view_material': 'View Material',
  'view_model': 'View Model',
  'view_materials': 'View Materials',
  'view_products': 'View Products',
  'view_photo': 'View Photo',
  'view_processphases': 'View Process Phases',
  'view_productionline': 'View Production Line',
  'view_productionlinehistoryperformance': 'View Production Line History Performance',
  'view_workstationhistoryperformance': 'View Workstation History Performance',
  'view_profile': 'View Profile',
  'view_resourceallocation': 'View Resource Allocation',
  'view_stepinstruction': 'View Step Instruction',
  'admin': 'Admin',
  'view_tool': 'View Tool',
  'view_user': 'View User',
  'view_workinstruction': 'View Work Instruction',
  'employee_change_password': 'View Employees Password Change',
  'view_workstation': 'View Workstation',
  'view_biometry': 'View Biometry',
  'view_client': 'View Client',
  'view_evaluationsettings': 'View Evaluations Configurations',
  'view_workstationcurrentevaluation': 'View Current Evaluations by Workstation',
  'view_actions': 'View FMEA Actions',
  'view_cause': 'View FMEA Causes',
  'view_control': 'View FMEA Control',
  'view_controlaction': 'View FMEA Control Actions',
  'view_effect': 'View FMEA Effects',
  'view_failuretype': 'View FMEA Failure Types',
  'view_fmea': 'View FMEA',
  'view_stageprocess': 'View FMEA Stage Process',
  'view_fmeastageprocess': 'View FMEA Stage Process',
  'view_stepprocess': 'View FMEA Step Process',
  'view_fmeastepprocess': 'View FMEA Step Process',
  'view_potentialfailure': 'View FMEA Potential Failure',
  'view_pontetialfailure': 'View FMEA Potential Failure',
  'add_gedtechconfig': 'Add GED Configuration',
  'change_gedtechconfig': 'Update GED Configuration',
  'delete_gedtechconfig': 'Delete GED Configuration',
  'resource_allocation_admin': 'Resource Allocation Administrator',
  'e_processflow': 'Delete Process Flow',
  'i_processflow': 'Add Process Flow',
  'v_processflow': 'View Process Flow',
  'w_processflow': 'Update Process Flow',
  'view_processflow': 'View Process Flow',
  'view_suggestion': 'View Suggestion',
  'view_workinstructiontool': 'View Work Instruction Tools',
  'view_product': 'View Product',
  'view_wastegeneration': 'View Waste Generation',
  'add_workinstructionstation': 'Add Work Instruction and Workstation Association',
  'change_workinstructionstation': 'Update Work Instruction and Workstation Association',
  'delete_workinstructionstation': 'Delete Work Instruction and Workstation Association',

  'public': 'Public',

  'label-unlimited': 'Unlimited',
  'report-generate presence list': 'Generate presence list',
  'msg-evaluation-invalid' : 'Number of attempts exceeded.',
  'title-evaluation-error' : 'Evaluation Invalid',
  'label-line-station': 'Line/Station',
  'label-line': 'Line',
  'label-station': 'Station',
  'label-elaborate': 'Elaborate',
  'label-reviewed-by': 'Reviewed by',
  'label-approved-by': 'Approved by',
  'label-epi-esd': 'IPE/ESD',
  'label-epi-and-esd': 'IPE\'s and ESD\'s',
  'label-select-epi-and-esd': 'Select IPE\'s and ESD\'s',
  'label-process': 'Process',

  'label_flowchart_edit': 'Edit flowchart',
  'label-shapes': 'Shapes',
  'label-arrows': 'Arrows',
  'label-text': 'Text',
  'label-height': 'Height',
  'label-width': 'Width',
  'label-edit-element': 'Edit Element',
  'label-adjust-graph': 'Adjust Page',
  'label-select-the-item': 'Select the item',
  'label-amount': 'Amount',


  'title-solicitation': 'Solicitation',
  'label-document-type': 'Document type',
  'label-document-code': 'Document code',
  'label-document-name': 'Document name',
  'label-model': 'Document Model',
  'label-department': 'Department',
  'label-scribe': 'Scribe',
  'label-approver': 'Reviewer',
  'label-homologator': 'Approver',
  'label-branch': 'Branch',
  'label-document-description': 'Description',
  'label-document-version': 'Version',
  'label-document-date': 'Date',
  'title-document-history' : 'History',
  'label-document-history' : 'History',
  'label-bt-close' : 'Close',
  'title-femea' : 'FMEA',
  'label-solicitation-homologation': 'Send for approval on GED',
  'label-export' : 'Export',

  'label_security_alert': 'Security alert',
  'label_quality_alert': 'Quality alert',
  'label_home': 'HOME',
  'title-fmea': 'FMEA',
  'title-nb-fmea': 'FMEA Code',
  'label_step_process': 'Process steps',
  'label_stage_process': 'Phases of the process',
  'label_number_fmea': 'FMEA Code',
  'label_customer_participant': 'Customer participant',
  'title_team_involved': 'Team involved',
  'label_selected_item': 'Select the item.',
  'label_edit_data': 'Edit data',
  'label_go_to_FMEA': 'Go to the FMEA',
  'label-recommended-actions': 'Recommended actions *',
  'label-recommended-actions-tool-tip': 'What are the recommended actions to improve detection and / or prevention?',
  'label-actions-taken-tool-tip': 'What actions have been taken and which RPN has been recalculated? Include the end date.',
  'label-owner-tool-tip': 'Responsible for action.',
  'label-potencial-failure-model-tool-tip': 'How can this main entry fail?',
  'label-potencial-failure-effect-tool-tip': 'What impact does this defect have on the output?',
  'label-causes-power-tool-tip': 'What causes can lead to the problem in this main entry?',
  'label_current_control-tool-tip': 'What controls / procedures exist to prevent this failure from occurring?',
  'label-actions-taken': 'Actions taken',
  'label-potencial-failure': 'Potential Failure',
  'label-potencial-failure-mode': 'Potential failure mode *',
  'label-potencial-failure-effect': 'Potential failure effect *',
  'label-severity': 'SEV',
  'label-causes-power': 'Potential causes *',
  'label-occurrence': 'OCC',
  'label-current-controls': 'Current Controls',
  'label-detection': 'DET',
  'label-rpn': 'RPN',
  'label-adjusted-rpn': 'Adjusted RPN',
  'label-actions': 'Actions',
  'labe_sequence': 'Sequence',
  'label_add_edit_steps': 'Add/Edit Step Process',
  'label_duplicate': 'Duplicate',
  'label_RPN_low_limit': 'RPN low limit',
  'label_RPN_above_limit': 'RPN above limit',
  'label_delete_actions': 'Delete actions',
  'label_current_control': 'Current controls',

  'label_recommended_actions': 'Recommended actions *',
  'label_actions_taken': 'Actions taken',
  'label_add_failure_mode': 'Add failure mode',
  'label_edit_failure_mode': 'Edit Failure Mode',

  'label_minimal_consent_of_the_client': '1 Minimal consent of the client',
  'label_some_consent': '2 - 3 Some consent',
  'label_some_dissatisfaction': '4 - 6 Some dissatisfaction',
  'label_high_dissatisfaction': '7 - 8 High dissatisfaction',
  'label_catastrophic': '9 - 10 Catastrophic',

  'label_improvavel': '1 - Unlikely',
  'label_little': '2 - 3 Little',
  'label_occasionally': '4 - 6 Occasionally',
  'label_repeatedly': '7 - 8 Repeatedly',
  'label_customer_not_satisfied': '9 - 10 Customer not satisfied',

  'label_surely_detectable': '1 - 2  Surely detectable',
  'label_good_chance_of_detection': '3 - 4 Good chance of detection',
  'label_maybe_detectable': '5 - 6 Maybe detectable',
  'label_almost_impossible_detect': '7 - 8 It is almost impossible to detect',
  'label_not_detectable': '9 - 10 Not Detectable',

  'label_failure_severity': 'S = Failure severity',
  'label_probability_occurrence': 'P = Probability of occurrence',
  'label_possibility_detection': 'D = Possibility of detection',



  'title-register-biometry': 'Register Biometry',
  'title-insert-leader-biometry': 'Insert leader biometry',
  'label-employee-wait-biometry': 'Waiting fingerprint...',
  'label-employee-recognized-biometry-error': 'Biometry reading error. Try again.',
  'label-employee-recognized-biometry-success': 'Successfully recognized biometry.',

  'label-evaluation-leader-not-valid': 'Invalid leader biometry. Leader not recognized.',

  'ELABORATION'  : 'DRAFT',
  'APPROVAL': 'IN REVISION',
  'HOMOLOGATION' : 'IN APPROVAL' ,
  'FINALIZED' : 'APPROVED' ,
  'CANCELED' : 'CANCELED',
  'INVALIDING' : 'IN INVALIDATION' ,
  'OBSOLETE' : 'FILED',
  'DISAPPROVED': 'DISAPPROVED',
  'REVIEW' : 'REVIEW',
  'REVIEWING' : 'REVIEWING',
  'label-email' : 'Email',

  'NO_EMAIL_YOU_USER' : 'You must have an email address.',
  'NO_USER_EMAIL_APPROVER' : 'It is necessary the approver to have an email and a registered user.',
  'NO_USER_EMAIL_HOMOLOGATOR' : 'The homologator must have an email and a registered user.',
  'SCRIBE_NOT_FOUND_GED' : 'You must have a user with the same email in the ged. Contact your System Administrator.',
  'APPROVER_NOT_FOUND_GED' : 'The Approver must have a user with the same email in the ged. Contact your System Administrator.',
  'HOMOLOGATOR_NOT_FOUND_GED' : 'The homologator should have a user with the same email in the ged. Contact your System Administrator.',
  'label_wecome': 'Welcome to',
  'label_system': 'a system of',
  'label_home_access': 'Access the menu for more information.',
  'close' : 'Close',
  'save' : 'Save',
  'label-create-copy' : 'Create copy',
  'title-document-clone' : 'Create copy',
  'exclude_error' : 'Error deleting item. It is associated in another registry',

  'start-evaluation': 'Start Test',

  'label-pdf': 'Export',

  'label-text-box': 'Text Box',
  'label-font-size': 'Font Size',
  'label-font-color': 'Text Color',
  'label-flowchart-config': 'Flow chart configuration',
  'label-view-new-tab': 'View in a new tab',
  'MGS_CONTAINS_DOCUMENT_COD' : 'A document with this same code already exists. Would you like to submit a new review?',

  'REQUIRED_DESCRIPTION' : 'Description Required',
  'REQUIRED_CODE' : 'Code Required',
  'REQUIRED_CLIENT' : 'Required FMEA Client',
  'REQUIRED_STAGE_PROCESS' : 'FMEA stage required',
  'REQUIRED_STEP_PROCESS' : 'Required FMEA Step',
  'REQUIRED_USER' : 'Required user',
  'REQUIRED_TEAM_INVOLVED_TWO' : 'You need at least two people involved.',
  'REQUIRED_FMEA_ONE_STEP' : 'Required FMEA Step',
  'REQUIRED_ONE_STAGE_ON_STEP' : 'Step Stage Required',
  'REQUIRED_POTENTIAL_FAILURE_ON_STAGE' : 'Required Step Potential Failure',
  'REQUIRED_POTENTIAL_FAILURE_MODES' : 'Potential Failure Required',
  'REQUIRED_POTENTIAL_FAILURE_EFFECTS' : 'Effects of Potential Failure Required',
  'REQUIRED_POTENTIAL_FAILURE_SEVERITY' : 'Potential Failure Severity Required',
  'REQUIRED_POTENTIAL_FAILURE_CAUSES' : 'Causes of Potential Failure Required',
  'REQUIRED_POTENTIAL_FAILURE_OCCURRENCE' : 'Potential Failure Occurrence Required',
  'REQUIRED_POTENTIAL_FAILURE_DETECTION' : 'Potential Failure Detection Required',
  'REQUIRED_RPN_REF' : 'RPN Reference required',
  'label-add-fmea': 'Add FMEA Data',
  'title-file-version' : 'Solicitation',
  'title-type' : 'Type',
  'title-author' : 'Author',
  'Identification Label' : 'Identification Label',
  'Standard Work Instruction' : 'Standard Work Instruction',
  'Operational Work Instruction	' : 'Operational Work Instruction	',
  'Master List' : 'Master List',
  'Standard Operating Procedure' : 'Standard Operating Procedure',
  'Operational Register' : 'Operational Register',
  'Management System Manual' : 'Management System Manual',
  'Standard Forms		' : 'Standard Forms		',
  'Failure Mode and Effects Analysis ' : 'Failure Mode and Effects Analysis ',
  'Polyci' : 'Policy',
  'Process Mapping' : 'Process Mapping',
  'Engineering Change' : 'Engineering Change',
  'External Documents' : 'External Documents',

  'label_prazo': 'Deadline',
  'label_title_docs': 'Documents Submissions',
  'label_type_docs': 'Document type',
  'label_code_docs': 'Document code',
  'label_arquivo_pdf': 'Select PDF file *',
  'label_arquivo_editavel': 'Select edit file *',
  'label_interessed': 'Concerned parties',
  'title-ged': 'GED',
  'title-file-version-task' : 'Pending Tasks',
  'title-deadline': 'Deadline',
  'label-download': 'Download',
  'label-approve': 'Approve',
  'label-desapprove': 'Disapprove',
  'label-confirm-remove-file': 'Do you want to remove this item?',
  'label-send-approval': 'Send for Revision',
  'label-send-homogate': 'Send for Approve',
  'label-homologate': 'Approve',
  'label-new-process': 'Restart Process',
  'label-request-review': 'Request Review',
  'title-current-document' : 'Current Documents',
  'add_folder' : 'Add Folder',
  'rename_folder' : 'Rename Folder',
  'detail' : 'Detail',
  'title-drawing-up-documents' : 'Drawing up documents',
  'title-add-document': 'Add document',
  'title-edit-document': 'Edit document',
  'importing' : 'Importing',
  'importing-production-lines' : 'Importing Production Lines',
  'label_local': 'Destination folder',
  'label_select': 'Select',
  'label_reviewer': 'Reviewer',
  'label-move': 'Move',
  'task-expired': 'Expired Task',
  'file_editable' : 'Editable File',
  'file_pdf' : 'PDF File',
  'select_destination_of_file' : 'Select destination of file.',
  'required_field' : 'Required field',
  'label_editable': 'Editable',
  'label_file_editable': 'Editable file',
  'label_latest_version': 'Latest version',
  'label-search': 'Search',
  'label-search-by-code': 'Search by Code',
  'label-search-by-name': 'Search by Name',
  'label-last-revision': 'Last Revision',
  'label-file-formart': 'File Formart',
  'label-revision': 'Revision',
  'label-open': 'Open Folder',
  'current_documents' : 'Current Documents',
  'select_folder' : 'Select Folder',
  'local' : 'Local',
  'label-reprove-justification': 'Reprove Justification',
  'placeholder-justification': 'Justification',
  'VALID_EMAIL': 'invalid email',
  'toast-block-delete': 'There is an issue linked to this evaluation.',
  'label_permission_allocated': 'Permission allocated',
  'label_title_solicitation': 'Submissions of documents',
  'already-exists-login' : 'Login already exists',
  'label-subscriber': 'Subscriber',
  'label-request-revision' : 'Request Revision',
  'obsolte_documents' : 'Filed Documents',
  'label-invalidate-document' : 'Invalidate document',
  'label-request-invalidation' : 'Request Invalidation',
  'label-confirm-invalidate-document' : 'Do you really want to invalidate this item?',
  'label-min-number-characters' : 'Minimum number of characters',
  'label-existing-doc' : 'Existing doc.',
  'label-recover': 'Recover',
  'label-folder': 'Folder',
  'label-search-production-line': 'Search by Production Line',
  'TRAINED': 'Trained employee',
  'WITHOUT_TRAINING': 'Untrained employee',
  'LOGGED_OFF': 'Tread starter',
  'IN_TRAINING': 'Training collaborator',
  'title-setting-tracking-dialog': 'Panel Settings',
  'title-setting-tracking-dialog-sub': 'Time and View of Lines',
  'label-time-swap': 'Time',
  'link' : 'Link',
  'label-deallocate': 'Deallocate',
  'label-reallocate': 'Reallocate',
  'label-justification': 'Justification',

  'label-place-holder-quality': 'Quality Description',
  'label-place-holder-seg': 'Security Description',
  'report_workstation': 'Workstation / Employee History',
  'documents' : 'Documents',
  'document_name' : 'Document Name',
  'description_version' : 'Reason for submission',
  'document-type': 'Document type',
  'label-search-document-type':  'Search by Document type ',
  'title-document-type-add': 'Add Document type',
  'label-description-type-document': 'Description in Portuguese',
  'label-description-type-document-en': 'Description in English',
  'label-branch-search': ' Search by Branch',
  'title-branch': 'Branch',


  'REQUIRED_EDITABLE_FILE' : 'Required the editable file.',
  'REQUIRED_PDF_FILE' : 'Required the pdf file.',

  'REQUIRED_MATERIAL_TOOLS' : 'Required Materials and Tools.',
  'REQUIRED_NAME' : 'Required name.',
  'REQUIRED_PROCESS_PHASE' : 'Required Process Phase.',
  'REQUIRED_MODELS' : 'Requires any model associated to the Work Instruction',
  'REQUIRED_DESCRIPTION_NOTES' : 'Required Security Alert.',
  'REQUIRED_STEPS' : 'Required steps',
  'required_interested_parts' : 'Required Concerned parties',
  'document-details': 'Document Details',
  'label-delete-all': 'Delete all',
  'label-delete-select': 'Delete selected',
  'report_report_rotation': 'Generate Relay List',
  'required_profiles' : 'Required Profile.',

  'approver_file'  :	'Can approver Files',
  'homologator_file'  :	'Can homologate Files',
  'scribe_file'  :	'Can Scribe Files',
  'adm_file'  :	'Can administrate Files',
  'view_editable_file'  :	'Can view editable Files',
  'label_save_caster': 'Save caster',
  'label_add_group': 'Add group',
  'label_group': 'Group',
  'label-automatic-rotation': 'Automatic Rotation',
  'label-confirm-stop-caster': 'Do you want to finalize auto-caster?\nAll employees will be deallocated from their work station..',

  'title-department-add': 'Add Department',
  'title-department': 'Department',
  'title-go-fmea': 'Go to Fmea',
  'evaluation-associated': 'There is an evaluation associated with this WI.',
  'not-selected' : 'Not Selected',
  'redirect-title': 'Redirection',
  'unsigned-user' : 'Unsigned task for this user',
  'task-finalized-user' : 'Task completed. To check in please login again.',

  'label__add_decription': 'Add description and Type',
  'label_type_laia': 'Types',
  'title-risk-factor': 'Risk Factor',
  'PHYSICAL_RISK': 'Physical',
  'BIOLOGICAL_RISK': 'Biological',
  'CHEMICAL_RISK': 'Chemical',
  'others_RISK': 'Others',
  'ERGONOMIC_RISK': 'Ergonomic',
  'ACCIDENTS_RISK': 'Accident',
  'label-risk-code-search': 'Code',
  'label-risk-description-search': 'Description',
  'label-risk-version-search': 'Version',
  'label-risk-type-search': 'Type',
  'ALL_TYPES': 'All types',
  'title-risk-factor-add': 'Add Risk Factor',
  'label-risk-description': 'Description',
  'label-risk-version': 'Version',
  'label-risk-code': 'Code',
  'label-risk-type': 'Type',
  'label-current-version': 'Current Version',

  'label_laia_combination': 'Combination LAIA',

  'label_classification': 'Classification',

  'label_aspects': 'Environmental Aspects',
  'label_impacts': 'Environmental impacts',
  'label_control': 'Operational control',
  'label_laia': 'Association LAIA',
  'label_create_laia': 'Register LAIA',

  'label_description_risk': 'Description',
  'label_version_risk': 'Version',
  'label_code_risk': 'Code',
  'label_type_risk': 'Type',
  'label_list_risk': 'Risk Factor',
  'label-control-measure': 'Control Measure',
  'title-register-signature': 'Register Signature',
  'clear': 'Clear',
  'signature' : 'Signature',

  'label-material-image': 'Material Image',

  'quiz-audit' : 'Audit Form',
  'questions' : 'Questions',
  'question-add': 'Add Quenstion',
  'label-register-search': 'Search by Register',
  'label-resolved-checked': 'Resolve marked suggestions',
  'title-control-plan' : 'Control Plan',
  'label-code-control-plan' : 'Código Control Plan',
  'label-type-control-plan' : 'Type',
  'label-client-control-plan' : 'Client',
  'label-model-control-plan' : 'Model',
  'label-dt-create-control-plan' : 'Date Create',
  'label-situation-control-plan' : 'Situation',
  'label-version-control-plan' : 'Version',

  'title-homologated-at' : 'Homologated date',
  'audit' : 'Audit',
  'result' : 'Result',
  'model' : 'Model',
  'work-instruction' : 'Work Instruction',
  'status' : 'Status',
  'validity' : 'Validity',
  'implementation' : 'Implementation',
  'cycle' : 'Cycle',
  'responsible' : 'Responsible',
  'auditor' : 'Auditor',
  'ACCORDANCE' : 'C',
  'NOT_IN_ACCORDANCE' : 'NC',
  'AUDIT_PENDING' : 'Pend',
  'AUDIT_WAITING_ACTIONS' : 'Waitting Actions',
  'AUDIT_WAITING_VALIDATION' : 'Waitting Validation',
  'AUDIT_DONE' : 'OK',
  'additional_data' : 'Additional data',
  'AUDIT_NEW' : 'New',
  'AUDIT_STARTED' : 'Started',
  'shift' : 'Shift',
  'area' : 'Area',
  'bt-accordance' : 'Accordance',
  'bt-not-accordance' : 'Not accordance',
  'start-audit' : 'Perform Audit',
  'not-accordance-description' : 'Description of non-conformity',
  'questions-dialog-audit' : 'Required answer all questions.',
  'questions-dialog-audit-accordance' : 'Audit completed successfully, after finishing, you will not be able to edit.',
  'questions-dialog-audit-not-accordance' : 'Audit completed, there are nonconforming items. After completing, the person in charge must fill in: Root Cause, Immediate Action and Corrective Action.',
  'questions-dialog-audit-not-accordance-action' : 'Saved successfully, there are corrective actions. The Auditor must validate them and include Evidence of Efficacy.',
  'questions-dialog-audit-not-accordance-done' : 'Audit completed successfully. After finishing, you will not be able to edit.',
  'questions-dialog-audit-done' : 'Audit is now complete  and can no longer be edited.',
  'required_audit_field_actions':'Required fields: Root Cause, Immediate Action and Corrective Action..',
  'required_audit_field_validate':'Required include  Evidence of Efficacy.',
  'root_cause' : 'Root Cause',
  'immediate_action' : 'Immediate Action',
  'corrective_action' : 'Corrective Action',
  'evidence_of_effficacy' : 'Evidence of Efficacy',
  'title-evidence_of_effficacy' : 'Evidence of Efficacy',
  'the_actions_effective' : 'Were the actions effective?',
  'LABEL_FREQUENCY': 'Frequency',
  'INCOMPLETE_FIELDS': 'Incomplete fields',
  'LABEL_CONTROL_PLAN_MACHINE': 'Machine, Device, Jig, Tool for Manufacture',
  'LABEL_CONTROL_PLAN_PRODUCT': 'Product, Specification Process, Tolerance',
  'LABEL_CONTROL_PLAN_MEASUREMENT': 'Measurement of technical evaluation',
  'LABEL_CONTROL_PLAN_METHOD': 'Control method',
  'LABEL_CONTROL_PLAN_ACTION': 'Reaction Plan',
  'LABEL_SIZE': 'Size',
  'LABEL_FEATURE': 'Feature',
  'LABEL_METHOD': 'Method',

  'confirm_current' : 'Do you want to change to current?',
  'host' : 'Host',
  'port' : 'Port',
  'username' : 'User Name',
  'from_email' : 'From Email',
  'fail_silently' : 'Fail Silently',
  'use_tls' : 'Use TLS',
  'current' : 'Current',
  'email-config' : 'Email Config',
  'bt-send-mail-test' : 'Send Test Email',
  'email_to' : 'To',
  'data' : 'Data',
  'version' : 'Version',
  'required_user_employee' : 'The Responsible must have a login and password',
  'audit-task' :'Audit Tasks',
  'QUIZ_AUDIT_NOT_CONTAINS_QUESTIONS': 'Audit Form not contains questions',
  'CONFIRM_ADD_BIOMETRY': 'Do you want to register biometrics?',
  'label-step-fmea': 'Step Process',
  'label-stage-fmea': 'Stage Process',
  'label-provider-control-plan' : 'Supplier',
  'label-provider-outher-control-plan' : 'Other Supplier Approvals',
  'label-client-plan' : 'Customer',
  'label-others-client-plan' : 'Other Customer Approvals',
  'label-export-xls-control-plan': 'Export XLSX',
  'check_status_on_ged':'Check status on GED',
  'document_not_found_on_ged' : 'Document not found on GED',
  'processing' :'Processing...',
  'labe-alter-cpf' : 'Change Info',
  'labe-cpf' : 'CPF',
  'cannot-deleted-user-create' : 'Employee can not be deleted because you have a login created',
  'cannot-deleted-employee-alocate' : 'Employee can not be deleted because he / she is allocated in a position',
  'audit_not_accordance' : 'Not Accordance',
  'audit_accordance' : 'Accordance',
  'audit_new' : 'New',
  'audit_started' : 'Started',
  'save_image' : 'Save as image',
  'audits_without_actions':'Audits without actions',
  'audit-area-not-accordance' : 'Nonconformity by Area',
  'audit-model-not-accordance' : 'Nonconformity by Model- Area:',
  'fmea_vs_controlplan': 'FMEA x Control Plan',
  'without_control_plan': 'FMEA without Control Plan',
  'with_control_plan': 'FMEA with Control Plan',
  'no_user' : 'No login registered',
  'pedding' : 'Pedding',
  'done' : 'Done',
  'evaluation_pedding': 'Pending Training',
  'view-img': 'Preview',
  'reproveed' :'Reproveed',
  'label-spot-error': 'Error trying save hotspot. Try again.',
  'label-load-workstations-error': 'Error trying load workstations.',
  'label-color': 'Color',
  'title-plant-view': 'Plant',
  'label-qty_evaluation' : 'Training Qty',
  'evaluation-not-performed' : 'Evaluation Not Performed',
  'area-all': 'All areas',
  'connect-erro-to-ged': 'Error connecting to GEDWEB',
  'label-process-flow-preview': 'Preview',
  'The fields quizAudit, statement must make a unique set.' : 'Question already exists.',
  'workstation-production-line-exist' : 'Workstation already registered in the plant',
  'The fields name must make a unique set.': 'Item already exist.',
  'send-to-ged' : 'Send to Ged',
  'material-it-subtitle': '* Only five Materials will be shown on IT export.',
  'model-it-subtitle': '* Only three Models will be shown on IT export.',
  'start_date': 'Start date',
  'label-bt-exit': 'Exit',
  'color-picker': 'Color Picker',

};
