export const LANG_PT_NAME = 'pt';

export const LANG_PT_TRANS = {
  'title-language': 'Idioma',
  'label-generic-hello': 'Olá, ',
  'title-profiles': 'Perfis',
  'title-users': 'Usuários',

  'title-documents': 'Documentos',
  'title-work-instruction': 'Instrução de trabalho',
  'WORK_INSTRUCTION_PROCESS': 'Instrução de trabalho Processo',
  'WORK_INSTRUCTION_QUALITY': 'Instrução de trabalho Qualidade',
  'CREATE_NEW_WORK_INSTRUCTION': 'Criar nova Instrução de Trabalho',
  'title-work-instruction-and-model': 'Instrução de trabalho e Modelos',
  'title-tools': 'Ferramentas',
  'title-models': 'Modelos',
  'title-materials': 'Materiais',
  'title-products': 'Produtos',
  'title-process-flow': 'Fluxo de Processo',
  'title-process-phase': 'Fases de Processo',
  'title-ipe': 'EPI\'s e ESD\'s',
  'title-production-line': 'Linha de Produção',
  'title-flow-date': 'Linha de Produção',
  'title-trainings': 'Treinamento',
  'title-evaluation': 'Avaliação',
  'title-resource-allocation': 'Alocação de Colaboradores',
  'title-performance-panel': 'Painel de Desempenho',
  'title-tracking-panel': 'Painel de Rastreamento',
  'title-biometry': 'Biometria',
  'trainings-tips': 'Resultado das avaliações realizadas',

  'title-quality-notes': 'Notas de Qualidade',
  'title-waste-generation': 'Geração de Resíduos',
  'title-general-notes': 'Notas Gerais',
  'title-code': 'Código',
  'label-description-it': 'Descrição da IT',
  'label-code-it': 'Código',
  'label-code-it-suggestion': 'Código da IT',
  'label-model-it': 'Modelo',
  'label-action-taken': 'Ação Tomada',
  'label-resolve': 'Resolver',
  'label-version-it': 'Versão',
  'label-flow-project-add': 'Nome do Projeto',
  'label-flow-code-add': 'Código do Projeto',
  'label-flow-client-add': 'Cliente',
  'label-flow-owner-add': 'Responsável',
  'label-flow-approval-add': 'Aprovado por',
  'label-flow-flowChart-add': 'Nome do Fluxograma',
  'label-flow-status-add': 'Situação',
  'title-project': 'Nome',
  'title-client': 'Cliente',
  'title-owner': 'Responsável',
  'title-approval': 'Aprovado por',
  'title-flowchart': 'Fluxograma',
  'title-last-change': 'Atualização',
  'title-version': 'Versão',
  'title-status': 'Situação',
  'title-description': 'Descrição',
  'title-name': 'Nome',
  'title-standard-rpn': 'RPN Padrão',
  'title-severity': 'Severidade',
  'title-error': 'Erro',
  'title-basic-data': 'Dados Básicos',
  'title-side-nav-configuration': 'Configurações',
  'title-side-nav-configuration-profile': 'Configuração de Perfil',
  'title-step': 'Passo',
  'title-tool-add-tool': 'Adicionar Ferramenta',
  'title-model-add-model': 'Adicionar Modelo',
  'title-process-flow-add-flow': 'Dados do Fluxo',
  'title-data-from-it': 'Dados da IT',
  'title-process-phase-add-process-phase': 'Adicionar Fase de Processo',
  'title-materials-add-materials': 'Adicionar Material',
  'title-products-add': 'Adicionar Produtos',
  'title-ipe-add': 'Adicionar EPI',

  'title-number-posts': 'Qtd. de Postos',
  'title-number-employee-posts': 'Qtd. Colaborador/Postos',
  'title-employee': 'Colaborador',
  'title-workstation': 'Postos',
  'title-created-at': 'Data da Criação',

  'title-validity': 'Validade',
  'title-signin': 'Entrar',
  'title-welcome': 'Bem-vindo',
  'title-signin-guest': 'Entrar como Convidado',
  'title-signin-biometrics': 'Entrar com Biometria',
  'biometry_is_not_connected': 'Leitor Biométrico não está conectado',
  'biometry_cant_be_read': 'Não foi possível ler a biometria',

  'placeholder-general-description': 'Descrição',
  'placeholder-general-model': 'Modelo',

  'placeholder-password': 'Senha',
  'placeholder-username': 'Usuário',
  'placeholder-search-by-name': 'Buscar pelo nome',
  'placeholder-search-by-profile': 'Buscar por perfil',

  'placeholder-work-instruction-name': 'Nome da Instrução',
  'placeholder-work-instruction-code': 'Código da Instrução',
  'placeholder-work-instruction-stage-process': 'Fase do Processo',
  'placeholder-work-instruction-workplace-safety': 'Segurança no Trabalho',
  'placeholder-work-instruction-safety-environmental': 'Segurança Ambiental',
  'placeholder-work-instruction-impact-reaction-plan': 'Plano de Reação ao Impacto',
  'placeholder-work-instruction-model-code': 'Código do Modelo',
  'placeholder-work-instruction-model-description': 'Descrição do Modelo',
  'placeholder-material': 'Nome da Instrução',
  'placeholder-work-instruction-material-code': 'Código do Material',
  'placeholder-work-instruction-material-description': 'Descrição do Material',
  'placeholder-image-description': 'Descrição',

  'placeholder-production-line-leader': 'Líder de Produção',

  'label-general-name': 'Nome',
  'label-general-list-description': 'Descrição',
  'label-general-list-model': 'Modelo',
  'label-general-status': 'Status',
  'label-general-active': 'Ativo',
  'label-general-inactive': 'Inativo',
  'label-general-initial-date-search': 'Data Inicial',
  'label-general-final-date-search': 'Data Final',
  'label-general-undetermined': 'Indeterminado',
  'label-general-situation': 'Situação',
  'label-general-employee': 'Colaborador',
  'label-general-employees': 'Colaboradores',
  'label-workinstruction-view-product': 'Nome da IT ',
  'label-workinstruction-view-line-station': 'Linha/Posto',
  'label-workinstruction-view-it-code': 'Código da IT',
  'label-workinstruction-view-approver': 'Aprovador',
  'label-workinstruction-view-developer': 'Elaborador',
  'label-workinstruction-view-model-product': 'Modelos/Produtos',
  'label-models-and-product': 'Modelos e Produtos',
  'label-general-instructor': 'Instrutor',

  'label-work-instruction-materials': 'Materiais',
  'label-work-instruction-models': 'Modelos',
  'label-work-instruction-search': 'Pesquisar instrução de trabalho (I.T.)',
  'label-work-instruction-search-by-model': 'Pesquisar instrução de trabalho por modelo',
  'label-work-instruction-identification': 'Identificação da Instrução de Trabalho - I.T.',
  'label-started-workstation': 'Selecionar Posto de Trabalho Inicial',
  'label-work-instruction-ocupational': 'Instrução de Segurança do Trabalho e Ambiental',
  'label-work-instruction-basic-data-tab': 'Dados Básicos',
  'label-work-instruction-materials-tools-tab': 'Materiais e Ferramentas',
  'label-work-instruction-instructions-tab': 'Instruções de Trabalho',
  'label-work-instruction-sesmt-tab': 'SESMT',
  'label-work-instruction-list-type-name': 'Nome da IT',
  'label-work-instruction-list-date': 'Data de homologação',

  'label-tools-search': 'Pesquisar Ferramenta',
  'label-tool-description': 'Descrição da Ferramenta',

  'label-model-code-search': 'Pesquisar por Código',
  'label-model-product-search': 'Pesquisar por Produto',
  'label-model-description-search': 'Pesquisar por Descrição',
  'label-model-description': 'Descrição do Modelo',
  'label-model-code': 'Código do Modelo',

  'label-process-phase-description-search': 'Pesquisar por Descrição',
  'label-materials-search': 'Pesquisar por Materiais',
  'label-ipe-search': 'Pesquisar por EPI/ESD',
  'label-products-search': 'Pesquisar Produtos',
  'label-code-it-search': 'Pesquisar Código IT',
  'label-suggetion-search': 'Pesquisar Sugestão',
  'label-all-situation-search': 'Todas as Situações',
  'label-process-phase-description': 'Descrição da Fase de Processo',
  'label-materials-description': 'Descrição do Material',
  'label-products-description': 'Descrição do Produto',
  'label-code-description': 'Código do Produto',

  'label-production-line-description-search': 'Pesquisar por Descrição',
  'label-production-line-initial-date-search': 'Data Inicial',
  'label-production-line-final-date-search': 'Data Final',
  'label-production-line-model-search': 'Pesquisar por Modelo',
  'label-production-line-leader': 'Líder de Produção',
  'label-production-line-list-qty-workstation': 'Qtd. Postos',
  'label-line-production-list-validity': 'Validade',

  'placeholder-production-line-qty-workstation': 'Qtd. de Postos',
  'placeholder-production-line-validity': 'Validade',
  'placeholder-production-line-undetermined-validity': 'Validade Indeterminada',

  'label-paper': 'Papéis',
  'label-plastics': 'Plásticos',
  'label-glasses': 'Vidros',
  'label-metals': 'Metais',
  'label-not-recyclable': 'Não Recicláveis',
  'label-dangerous-wastes': 'Resíduos Perigosos',
  'label-not-generate-waste': 'Não gera Resíduos',
  'label-profile-search': 'Pesquisar perfil',
  'label-profile-permission': 'Permissões',
  'label-profile-description': 'Descrição de Perfil',
  'label-ipe-description': 'Descrição de EPI',
  'label-profile-visualization': 'Visualizar',
  'label-profile-create': 'Adicionar',
  'label-profile-edit': 'Editar',
  'label-profile-delete': 'Excluir',
  'label-result-all': 'Todos os resultados',
  'label-evaluation-situation-all': 'Todos os status',
  'label-evaluation-situation-avaiable': 'Disponível',
  'label-evaluation-situation-expired': 'Expirado',
  'label-evaluation-situation-planned': 'Planejado',
  'label-evaluation-quiz-name': 'Nome do Quiz',

  'label-flow-status-sketch': 'Rascunho',
  'label-flow-status-approval': 'Em Aprovação',
  'label-flow-status-homologation': 'Homologado',
  'label-flow-status-inactive': 'Inativo',


  'label-bt-back': 'Voltar',
  'label-bt-save-draft': 'Salvar Rascunho',
  'label-bt-next': 'Próximo',
  'label-bt-add-new': 'Adicionar Novo',
  'label-bt-edit': 'Editar',
  'label-bt-save': 'Salvar',
  'label-bt-exit-workstation': 'Desalocar do Posto',
  'label-bt-delete': 'Excluir',
  'label-bt-cancel': 'Cancelar',
  'label-bt-homologation': 'Enviar para Homologação',
  'label-bt-previus': 'Anterior',
  'label-bt-finish': 'Finalizar',
  'label-bt-export': 'Exportar',
  'label-bt-suggestion': 'Sugestão',
  'BT_OK': 'OK',
  'label-day': 'Dia',
  'label-work-instruction-name': 'Nome da instrução de trabalho',
  'label-status': 'Situação',
  'label-delete': 'Deletar',
  'label-duplicate': 'Duplicar',
  'label-edit': 'Editar',
  'label-details': 'Detalhes',
  'label-suggestions-it': 'Sugestão',
  'label-suggestions-description-it': 'Descrição da Sugestão',
  'label-new': 'Novo',
  'label-remove': 'Remover',
  'label-confirm-remove': '$description',
  'label-confirm-remove-item': 'Deseja remover esse item?',
  'label-active': 'Ativo',
  'label-inactive': 'Inativo',
  'label-all': 'Todos',
  'label-code': 'Código',
  'label-materials': 'Materiais',
  'label-description': 'Descrição',
  'label-description-revision': 'Descrição de Revisão',

  'label-products': 'Produtos',
  'label-suggestion': 'Sugestão',
  'label-details-suggestion': 'Detalhes da Sugestão',
  'label-situation': 'Situação',
  'label-filter-name': 'Filtrar por nome',
  'label-filter-code': 'Filtrar por código',
  'label-filter-by': 'Filtrar por',
  'label-filter': 'Filtro',
  'label-add-filter': 'Adicionar filtro',
  'label-active-filters': 'Filtros ativos',
  'label-clear-filters': 'Limpar filtros',
  'label-type': 'Tipo',
  'label-image-select': 'Selecionar Imagem',
  'label-done-register': 'Cadastro realizado',
  'label-pending-register': 'Cadastro pendente',
  'label-pending': 'Pendente',
  'label-closed': 'Fechada',
  'label-no-filter': 'Sem Filtro',
  'label-identification': 'Identificação',
  'label-add': 'Adicionar',
  'label-add-flow': 'Adicionar Dados de fluxo',
  'label-update': 'Atualizar',
  'label-restore': 'Restaurar',
  'label-key': 'Chave',
  'label-value': 'Valor',
  'label-cancel': 'Cancelar',
  'label-save': 'Salvar',
  'label-phase': 'Fase',
  'label-yes': 'Sim',
  'label-no': 'Não',
  'label-required': 'Obrigatório',
  'label-optional': 'Opcional',
  'label-parallel': 'Paralelo',
  'label-order': 'Ordem',
  'label-click-drag': 'Clique e arraste',
  'label-reports': 'Relatórios',
  'label-workstation-type-name': 'Descrição',
  'label-workstation-type': 'Tipo',
  'label-product': 'Produto',
  'label-read-date': 'Data de Leitura',
  'label-read-time': 'Tempo de Leitura',
  'label-people-quantity': 'Quantidade de Pessoas',
  'label-quantity': 'Qtd.',
  'label-accumulated-real-time': 'Tempo Real Acumulado',
  'label-accumulated-estimated-time': 'Tempo Estimado Acumulado',
  'label-logic-performance': 'Performance Lógica',
  'label-kijun-real-time': ' Tempo Real KIJUN',
  'label-kijun-performance': 'Performance KIJUN',
  'label-unscheduled-stops': 'Paradas Não Programadas',
  'label-schedule-stops': 'Paradas Programadas',
  'label-exclusion-stops': 'Paradas Excluídas',
  'label-selected-items': 'Itens selecionados',
  'label-available-items': 'Itens disponíveis',
  'label-no-selected-item': 'Nenhum item selecionado',
  'label-no-available-item': 'Nenhum item disponível',
  'label-place-holder-editor': 'Descrição do Passo',
  'label-place-holder-quality': 'Descrição de qualidade',
  'label-place-holder-seg': 'Descrição de segurança',
  'label-review': 'Revisão',
  'label-start-review' : 'Iniciar Revisão',
  'label-itens-of-page': 'Itens por página',
  'workstation_per_page': 'Postos por página',

  'label-edit-flowchart': 'Editar Fluxograma',

  'error-message-connection': 'Erro de conexão.',
  'error-message-not-found': 'Serviço não encontrado.',
  'message-error-retrieve-product': 'Não foi possível recuperar o produto.',
  'message-error-retrieve-bom': 'Não foi possível recuperar a BOM.',
  'message-error-retrieve-product-properties': 'Não foi possível recuperar as propriedades do produto.',
  'message-error-retrieve-product-map': 'Não foi possível recuperar as configurações do produto.',
  'message-error-retrieve-production-map': 'Não foi possível recuperar os roteiros do produto.',
  'message-error-retrieve-product-process': 'Não foi possível recuperar o tempo estimado de produção.',
  'message-error-delete-product': 'Existem registros associados a esse produto.',
  'message-error-delete-product-process': 'Existem registros associados ao tempo estimado de produção.',
  'message-error-delete-workstation-type': 'Existem registros associados a esse tipo de posto.',
  'message-error-delete-workstation': 'Existem registros associados a esse posto.',
  'message-error-delete-component': 'Existem registros associados a esse componente.',
  'message-error-delete-category': 'Existem registros associados a essa categoria.',
  'message-error-delete-production-line': 'Existem registros associados a essa linha de produção.',
  'message-error-delete-production-map': 'Existem registros associados a esse roteiro.',
  'message-error-delete-defect': 'Existem registros associados a esse defeito.',
  'message-error-update-item': 'Não foi possível alterar o item.',
  'message-error-delete': 'Erro ao excluir o item.',
  'message-error-value-bigger-than-expect': 'Valor deve ser menor que',
  'message-success-insert-item': 'Item cadastrado.',
  'message-success-update-item': 'Item atualizado.',
  'message-warning-register': 'Nenhum registro encontrado',

  'already-associated-work-instruction': 'Instrução de Trabalho já está associada.',


  'label-workstation-code': 'Código da estação de trabalho',
  'label-workstation-description': 'Descrição da estação de trabalho',
  'label-workstation-hostname': 'Hostname da estação de trabalho',
  'label-production-line-description': 'Descrição',
  'label-production-line-code': 'Código',
  'label-scrap': 'Refugo',
  'label-goal': 'Meta',
  'label-indicator': 'Indicador',
  'label-scrap-by-period': 'REFUGO_POR_PERIODO',
  'label-username': 'Nome de usuário',
  'label-profile': 'Perfil',
  'label-password': 'Senha',
  'label-old-password': 'Senha atual',
  'label-new-password': 'Nova senha',
  'label-password-confirmation': 'Confirmação da senha',
  'label-update-settings': 'Atualizar configurações',
  'label-name': 'Nome',
  'label-login': 'Login',
  'label-profile-name': 'Nome do perfil',
  'label-permissions': 'Permissões',
  'label-view': 'Visualização',
  'label-create': 'Criar',
  'label-required-fields': 'Campos Obrigatórios',
  'label-step': 'Passo',
  'label-register': 'Matrícula',
  'label-departament': 'Departamento',
  'label-last-access': 'Último acesso',
  'label-assign-profile': 'Atribuir perfil',

  'toast-success-title': 'Sucesso!',
  'toast-fail-delete-model-title': 'Este modelo não pode ser excluído, pois está associado a uma linha de produção!',
  'toast-attention-title': 'Atenção!',
  'toast-saved-successfully': 'Item salvo com sucesso',
  'toast-evaluation-not-approved': 'Atenção! Você não possui o treinamento para este posto de trabalho. Por favor, procure o líder da linha para providenciar o treinamento.',
  'toast-employee-allocated': 'É necessário desalocar o colaborador do posto anterior',
  'toast-complete-all-fields': 'Preencha todos os campos',
  'toast-ipe': 'Tipo de EPI inválido',
  'toast-deleted-successfully': 'Item removido com sucesso',
  'toast-updated-successfully': 'Item alterado com sucesso',
  'toast-error-title': 'Erro!',
  'toast-error-load': 'Erro ao carregar dados',
  'toast-token-expired': 'Sua sessão expirou',
  'toast-deleted-fmea-error': 'Existem itens cadastrados',
  'toast-request-review-successfully': 'Solicitação de Revisão enviada com sucesso.',
  'folder-not-empty': 'Apenas pastas vazias poderão ser excluídas',
  'toast-select-one-item': 'Selecione pelo menos um item!',
  'toast-deleted-error': 'Erro ao tentar deletar esse item.',


  'authentication': 'Autenticação',
  'username-or-password-invalids': 'Usuário ou senha inválidos',
  'user-not-found': 'Usuário não encontrado',
  'month-days': 'Dias do Mês',
  'period-days': 'Dias do Período',
  'performances': 'Performances',
  'performance': 'Performance',
  'logic': 'Lógica',
  'real': 'Real',
  'processes': 'Processos',
  'search': 'Buscar',
  'month': 'Mês',
  'year': 'Ano',
  'download-chart': 'Baixar gráfico',
  'view-list': 'Ver em lista',
  'msg-chart': 'Clique no gráfico para detalhar um processo',
  'date': 'Data',
  'update-date': 'Data de atualização',
  'serial': 'Serial',
  'process': 'Processo',
  'state': 'Situação',
  'approved': 'Aprovado',
  'reproved': 'Reprovado',
  'repairing': 'Em reparo',
  'scrap': 'Descartado',
  'terminated': 'Terminado',
  'remove-last-operation': 'Desfazer última operação',
  'generate-xls': 'Gerar arquivo XLS',
  'message-there-are-not-data': 'Não há dados para exibir no gráfico.',
  'serial-number-not-read': 'Não há leituras para o número de série informado.',
  'defects-quantity': 'Quantidade de Defeitos',
  'chart-legend': 'Legenda',
  'legend-defects': 'Tipos de Defeito',
  'start-date': 'Data Inicial',
  'end-date': 'Data Final',
  'read': 'Leitura',
  'binding': 'Amarração',
  'read-log': 'Leitura de log',
  'repair-workstation': 'Posto técnico',
  'packing': 'Embalagem',
  'oqc': 'OQC',
  'defect-record': 'Registro de defeito',
  'panel-management-view': 'Gestão à vista',
  'change-model': 'Troca de modelo',
  'workstation-type-update-success': 'Tipo de posto de trabalho alterado com sucesso.',
  'workstation-type-save-success': 'Tipo de posto de trabalho salvo com sucesso.',
  'description': 'Descrição',
  'code': 'Código',
  'category': 'Categoria',
  'product': 'Produto',
  'workstation-update-success': 'Posto de trabalho alterado com sucesso.',
  'workstation-save-success': 'Posto de trabalho salvo com sucesso.',
  'production-line-save-success': 'Linha de produção salva com sucesso.',
  'production-line-update-success': 'Linha de produção alterada com sucesso.',
  'next': 'Próximo',
  'previous': 'Anterior',
  'message-warning-inactive-item': 'Deseja inativar este item ( $workinstruction)?',
  'message-warning-active-item': 'O item ficará pendente de homologação. Deseja continuar?',

  'already-exist': 'Item já está cadastrado.',
  'already-selected': 'Item já está selecionado.',
  'already-used': 'Item já está sendo utilizado.',
  'cannot-deleted': 'Item não pode ser excluído',
  'menu-edit': 'Editar',
  'menu-view': 'Visualizar',
  'menu-delete': 'Excluir',
  'menu-create-preview': 'Criar Visualização',

  'label_module_production_line': 'Linhas de Produção',
  'label_module_models': 'Modelos',
  'label_module_workstation': 'Postos de Trabalho',
  'label_module_employee': 'Colaboradores',
  'label_module_tools': 'Ferramentas',
  'label_module_process_phases': 'Fases do Processo',
  'label_module_fmea': 'FMEA',
  'label_module_work_instruction': 'Instrução de Trabalho',
  'label_module_process_flow': 'Fluxo de Processo',
  'label_module_report': 'Relatórios',
  'label_module_instruction_visualization': 'Visualização da Instrução',
  'label_module_instruction_evaluation': 'Avaliação da Instrução',
  'label_module_evaluation_list': 'Lista de Avaliações',
  'label_module_profile_configuration': 'Configuração de Perfil',
  'label_module_employee_add': 'Adicionar colaborador',
  'label_work_station_add': 'Adicionar Posto de trabalho',
  'label_work_station_edit': 'Editar Posto de trabalho',
  'label-search-employee-departament' : 'Pesquisa por Departamento',
  'label-search-employee-profile': 'Pesquisa por Perfil',
  'label-employee-employeedata': 'Dados do colaborador',
  'label-employee-userdata': 'Dados do Usuário',
  'label-employee-register-biometrics': 'Cadastrar Biometria',
  'label-employee-edit-biometrics': 'Editar Biometria',
  'label-employee-search': 'Pesquisar por Colaborador',


  'label-import': 'Importar',
  'label-import-success': 'Importação Realizada com Sucesso',
  'label-file-invalid': 'Arquivo Inválido',
  'label-import-excel': 'Importar excel',


  'label-work-station': 'Posto de trabalho',
  'label-search-work-station': 'Pesquisa por Posto de trabalho',

  'label-search-project': 'Pesquisa por Nome',
  'label-search-code': 'Pesquisa por Código',

  'label-evaluation-basic-data': 'Dados Básicos da Avaliações',
  'label-evaluation-questions': 'Questões da Avaliação',
  'label-evaluation-general': 'Feedback Geral',
  'label-evaluation-attempts': 'Número de tentativas',
  'label-evaluation-time-over': 'Tempo esgotado!',
  'label-evaluation-accomplishment_time': 'Tempo de realização',
  'label-evaluation-name-quiz': 'Nome do Quiz',
  'label-evaluation-percent_approval': 'Mínima para aprovação',
  'label-evaluation-feedback_approved': 'Feedback aprovado',
  'label-evaluation-feedback_disapproved': 'Feedback reprovado',
  'label_evaluation_add': 'Adicionar Avaliação',
  'label_evaluation_edit': 'Editar Avaliação',
  'label_start': 'Início',
  'label-score': 'Nota',

  'label-question-data-question': 'Dados da Questão',
  'label-question-name-question': 'Nome da questão',
  'label-question-statement': 'Enunciado',
  'label-question-multiple': 'Múltipla escolha',
  'label-question-connect': 'Associar',
  'label-question-complete': 'Completar',
  'label-question-true-false': 'Verdadeiro ou Falso',
  'label-answer': 'Resposta',
  'label-true': 'Verdadeiro',
  'label-false': 'Falso',
  'msg_disapproved': 'Você foi reprovado com ',
  'msg_aproveed': 'Você foi aprovado com ',

  'label-bt-close-evaluation' : 'Fechar Avaliação',
  'retake_evaluation': 'Refazer avaliação',
  'TRUE OR FALSE': 'Verdadeiro ou Falso',
  'COMBINE': 'Associação',
  'MULTIPLE CHOICE': 'Múltipla escolha',

  'title-resource-allocation-add-employee': 'Adicionar Colaborador',

  'label-resource-allocation-edit': 'Editar Posto de Trabalho',
  'label-resource-allocation-register': 'Matrícula',
  'label-resource-allocation-relay': 'Revezamento em',
  'label-resource-allocation-qty-employees': 'Qtd. de colaboradores',
  'label-resource-allocation-workstation': 'Posto',
  'label-resource-allocation-relay-with': 'Faz revezamento com',

  'label-performance-panel-realized': 'Realizado',
  'label-performance-panel-not-realized': 'A Realizar',
  'label-performance-panel-expired-when': 'Expira em:',
  'label-performance-panel-expired': 'Expirado em: ',
  'label-performance-panel-conclusion-when': 'Conclusão em:',
  'label-performance-panel-instruction': 'Instrução:',
  'label-performance-panel-score-evaluation': 'Nota da avaliação',
  'label-performance-panel-evaluation-attempts': 'Tentativas',
  'label-performance-panel-production-line-workstation': 'Linha de Produção/Posto:',
  'label-performance-panel-all': 'Todos',
  'label-performance-panel-pending': 'Pendentes',
  'label-performance-panel-done': 'Realizados',
  'label-performance-panel-records': 'Registros',
  'label-performance-panel-record': 'Registro',
  'label-performance-panel-none-record': 'Registros',
  'label-performance-panel-my-results': 'Meus Resultados',
  'label-performance-panel-average': 'Média',
  'label-performance-panel-ranking-by': 'Ranking por',
  'label-performance-panel-workstation': 'Posto de Trabalho',
  'label-performance-panel-production-line': 'Linha de Produção',
  'label-performance-panel-company': 'Fábrica',
  'label-performance-panel-approbation-in-training': 'Em Treinamento',
  'label-performance-panel-approbation-apt': 'Apto',
  'label-performance-panel-approbation-apt-with-observations': 'Apto com observações',
  'label-performance-panel-approbation-inapt': 'Inapto',
  'label-performance-panel-approbation-title': 'Parecer Técnico',
  'label-approbation-status': 'Status',
  'label-approbation-note': 'Observação',

  'error-title-performance-panel-invalid-trainer': 'Treinador inválido',
  'error-performance-panel-invalid-trainer': 'Você não está alocado como treinador.',

  'error-max-alternatives' : 'Quantidade de alternativas não permitida. O máximo são de 5 alternativas.',
  'error-min-alternatives' : 'Quantidade de alternativas não permitida. O mínimo são de 3 alternativas.',

  'error-max-alternatives-with-photo' : 'Questão precisa ter pelo menos 1 imagem e 2 alternativas.',
  'error-not-selected-alternative' : 'É necessário selecionar uma alternativa como resposta.',
  'make_evaluation': 'Fazer avaliação',
  'invalid_address' : 'Endereço inválido!',
  'title-evaluation-view-error' : 'Erro',
  'bt-dialog-finalize' : 'Finalizar',
  'bt-dialog-cancel' : 'Cancelar',
  'dialog-attention-title': 'Atenção!',
  'questions-dialog-evaluation' : 'Deseja realmente finalizar o teste?',
  'subtitle-evaluation' : 'Questões não respondidas.',


  'add_logentry' : 'Pode adicionar entrada de log',
  'change_logentry' : 'Pode alterar a entrada de log',
  'delete_logentry' : 'Pode excluir entrada de log',
  'add_permission' : 'Pode adicionar permissão',
  'change_permission' : 'Pode mudar de permissão',
  'delete_permission' : 'Pode excluir permissão',
  'add_group' : 'Pode adicionar grupo',
  'change_group' : 'Pode mudar de grupo',
  'delete_group' : 'Pode excluir grupo',
  'add_contenttype' : 'Pode adicionar o tipo de conteúdo',
  'change_contenttype' : 'Pode mudar o tipo de conteúdo',
  'delete_contenttype' : 'Pode excluir o tipo de conteúdo',
  'add_session' : 'Pode adicionar sessão',
  'change_session' : 'Pode mudar de sessão',
  'delete_session' : 'Pode excluir sessão',
  'add_token' : 'Pode adicionar Token',
  'change_token' : 'Pode mudar o token',
  'delete_token' : 'Pode apagar o token',
  'add_user' : 'Pode adicionar usuário',
  'change_user' : 'Pode mudar o usuário',
  'delete_user' : 'Pode excluir o usuário',
  'add_department' : 'Pode adicionar departamento',
  'change_department' : 'Pode mudar de departamento',
  'delete_department' : 'Pode excluir o departamento',
  'add_employee' : 'Pode adicionar empregado',
  'change_employee' : 'Pode mudar o empregado',
  'delete_employee' : 'Pode excluir o funcionário',
  'add_evaluation' : 'Pode adicionar avaliação',
  'change_evaluation' : 'Pode alterar a avaliação',
  'delete_evaluation' : 'Pode apagar a avaliação',
  'add_material' : 'Pode adicionar material',
  'change_material' : 'Pode mudar o material',
  'delete_material' : 'Pode excluir material',
  'add_model' : 'Pode adicionar modelo',
  'change_model' : 'Pode mudar o modelo',
  'delete_model' : 'Pode excluir o modelo',
  'add_module' : 'Pode adicionar o módulo',
  'change_module' : 'Pode alterar o módulo',
  'delete_module' : 'Pode apagar o módulo',
  'add_occupation' : 'Pode adicionar ocupação',
  'change_occupation' : 'Pode mudar de ocupação',
  'delete_occupation' : 'Pode excluir a ocupação',
  'add_photo' : 'Pode adicionar foto',
  'change_photo' : 'Pode mudar de foto',
  'delete_photo' : 'Pode deletar foto',
  'add_processphases' : 'Pode adicionar fases do processo',
  'change_processphases' : 'Pode mudar as fases do processo',
  'delete_processphases' : 'Pode excluir fases do processo',
  'add_productionline' : 'Pode adicionar linha de produção',
  'change_productionline' : 'Pode mudar a linha de produção',
  'delete_productionline' : 'Pode excluir a linha de produção',
  'add_profile' : 'Pode adicionar perfil',
  'change_profile' : 'Pode mudar de perfil',
  'delete_profile' : 'Pode excluir o perfil',
  'add_profilepermission' : 'Pode adicionar permissão de perfil',
  'change_profilepermission' : 'Pode alterar permissão de perfil',
  'delete_profilepermission' : 'Pode excluir permissão de perfil',
  'add_question' : 'Pode adicionar uma pergunta',
  'change_question' : 'Pode mudar de pergunta',
  'delete_question' : 'Pode eliminar a pergunta',
  'add_questiontype' : 'Pode adicionar um tipo de pergunta',
  'change_questiontype' : 'Pode mudar o tipo de pergunta',
  'delete_questiontype' : 'Pode excluir o tipo de pergunta',
  'add_resourceallocation' : 'Pode adicionar alocação de recursos',
  'change_resourceallocation' : 'Pode alterar a alocação de recursos',
  'delete_resourceallocation' : 'Pode excluir alocação de recursos',
  'add_shift' : 'Pode adicionar mudança',
  'change_shift' : 'Pode mudar de turno',
  'delete_shift' : 'Pode excluir mudança',
  'add_stepinstruction' : 'Pode adicionar passos de instrução',
  'change_stepinstruction' : 'Pode mudar a instrução do passo',
  'delete_stepinstruction' : 'Pode excluir a instrução do passo',
  'add_tool' : 'Pode adicionar ferramenta',
  'change_tool' : 'Pode mudar a ferramenta',
  'delete_tool' : 'Pode excluir ferramenta',
  'add_workinstruction' : 'Pode adicionar instruções de trabalho',
  'change_workinstruction' : 'Pode mudar as instruções de trabalho',
  'delete_workinstruction' : 'Pode excluir instruções de trabalho',
  'add_workstation' : 'Pode adicionar estação de trabalho',
  'change_workstation' : 'Pode mudar a estação de trabalho',
  'delete_workstation' : 'Pode excluir estação de trabalho',
  'add_alternative' : 'Pode adicionar alternativa',
  'change_alternative' : 'Pode mudar de alternativa',
  'delete_alternative' : 'Pode excluir alternativas',
  'add_alternativeanswer' : 'Pode adicionar uma resposta alternativa',
  'change_alternativeanswer' : 'Pode mudar a resposta alternativa',
  'delete_alternativeanswer' : 'Pode excluir a resposta alternativa',
  'add_evaluationresult' : 'Pode adicionar o resultado da avaliação',
  'change_evaluationresult' : 'Pode alterar o resultado da avaliação',
  'delete_evaluationresult' : 'Pode excluir o resultado da avaliação',
  'add_questionanswer' : 'Pode adicionar uma pergunta',
  'change_questionanswer' : 'Pode mudar a resposta da pergunta',
  'delete_questionanswer' : 'Pode eliminar a pergunta',
  'title-evaluation-instruction': 'Instruções para avaliação',
  'before you begin' : 'Antes de você começar',
  'minutes' : 'minutos',
  'no_option_pause' : 'Não há opção para pausar. Certifique-se de que não haverá interrupções durante a avaliação.',
  'no_close_browser' : 'Você não pode fechar seu browser durante a avaliação.',
  'it_before_evaluation': 'É necessário ver as Instruções de trabalho antes da avaliação.',
  'label-bt-it' : 'Ver Instrução de Trabalho',
  'label-bt-evaluation' : 'Realizar avaliação',
  'subtitle-actions' : 'Veja a instrução de trabalho antes da avaliação.',
  'checkt-it-evaluation' : 'Eu declaro que vi a instrução de trabalho.',
  'trainings_per_employee': 'Treinamentos por Colaborador',
  'trainings_per_it': 'Colaborador por Instrução de trabalho',

  'no-workstations-associated' : 'Sem estações de trabalho associadas',
  'label-signature': 'Assinatura',

  'title_initial_month': 'Mês Inicial',
  'title_final_month': 'Mês Final',
  'title_qtd_partitions': 'Qtd. Participantes',


  'dashboard_evaluation': 'Acessar Painel de Desempenho',
  'dashboard_evaluation_all_employee': 'Acessar Painel de Desempenho de todos colaboradores',
  'view_question': 'Acessar Questão',
  'view_questionanswer': 'Acessar Respostas das Questões',
  'view_questiontype': 'Acessar Tipos das Questões',
  'view_alternative': 'Acessar Alternativa',
  'view_alternativeanswer': 'Acessar Respostas das Alternativas',
  'view_employee': 'Acessar Colaboradores',
  'view_evaluation': 'Acessar Avaliação',
  'view_evaluationresult': 'Acessar Resultado da Avaliação',
  'view_material': 'Acessar Materiais',
  'view_model': 'Acessar Modelos',
  'view_materials': 'Acessar Materiais',
  'view_products': 'Acessar Produtos',
  'view_photo': 'Acessar Fotos',
  'view_processphases': 'Acessar Fases de Processo',
  'view_ipe': 'Acessar "\'EPI\'s e ESD\'s\'"',
  'view_productionline': 'Acessar Linha de Produções',
  'view_productionlinehistoryperformance': 'Acessar Histórico de Desempenho por Linha de Produção',
  'view_workstationhistoryperformance': 'Acessar Histórico de Desempenho por Estações de Trabalho',
  'view_profile': 'Acessar Perfil',
  'view_resourceallocation': 'Acessar Alocação de Recursos',
  'view_stepinstruction': 'Acessar Passos das Instruções de Trabalho',
  'admin': 'Administrador',
  'view_tool': 'Acessar Ferramentas',
  'view_user': 'Acessar Usuários',
  'view_workinstruction': 'Acessar Instruções de Trabalho',
  'view_workstation': 'Acessar Estações de Trabalho',
  'view_biometry': 'Acessar Biometria',
  'view_client': 'Acessar Clientes',
  'view_evaluationsettings': 'Acessar Configuração de Avaliações',
  'view_workstationcurrentevaluation': 'Acessar Avaliação Atual por Posto de Trabalho',
  'view_actions': 'Acessar Ações FMEA',
  'view_cause': 'Acessar Causas FMEA',
  'view_control': 'Acessar Controle FMEA',
  'view_controlaction': 'Acessar Controle de Ações FMEA',
  'view_effect': 'Acessar Efeitos FMEA',
  'view_failuretype': 'Acessar Tipo de Falhas FMEA',
  'view_fmea': 'Acessar FMEA',
  'view_stageprocess': 'Acessar Etapas do Processo FMEA',
  'view_fmeastageprocess': 'Acessar Etapas do Processo FMEA',
  'view_stepprocess': 'Acessar Passos do Process FMEA',
  'view_fmeastepprocess': 'Acessar Passos do Process FMEA',
  'view_potentialfailure': 'Acessar Falhas Potenciais FMEA',
  'view_pontetialfailure': 'Acessar Falhar Potencias FMEA',
  'add_gedtechconfig': 'Adicionar Configurações GED',
  'change_gedtechconfig': 'Alterar Configurações GED',
  'delete_gedtechconfig': 'Excluir Configurações GED',
  'resource_allocation_admin': 'Administrador da Alocação de Recursos',
  'e_processflow': 'Excluir Fluxo de Processo',
  'i_processflow': 'Adicionar Fluxo de Processo',
  'v_processflow': 'Visualizar Fluxo de Processo',
  'w_processflow': 'Alterar Fluxo de Processo',
  'v_plantview': 'Visualizar Planta',
  'i_plantview': 'Adicionar Planta',
  'e_plantview': 'Excluir Planta',
  'w_plantview': 'Alterar Planta',
  'v_plantpoints': 'Visualizar Pontos Planta',
  'i_plantpoints': 'Adicionar Pontos Planta',
  'e_plantpoints': 'Excluir Pontos Planta',
  'w_plantpoints': 'Alterar Pontos Planta',
  'view_processflow': 'Acessar Fluxo de Processo',
  'view_suggestion': 'Acessar Sugestões',
  'view_workinstructiontool': 'Acessar Ferramentas de Instrução de Trabalho',
  'view_product': 'Acessar Produtos',
  'view_wastegeneration': 'Acessar Geração de Resíduos',
  'add_workinstructionstation': 'Acessar Associação Instrução de Trabalho e Posto de Trabalho',
  'change_workinstructionstation': 'Alterar Associação Instrução de Trabalho e Posto de Trabalho',
  'delete_workinstructionstation': 'Excluir Associação Instrução de Trabalho e Posto de Trabalho',
  'view_controlplan': 'Acessar Plano de Controle',
  'view_controlplandetail': 'Acessar Detalhes Plano de Controle',
  'view_controlplanprocess': 'Acessar Processos do Plano de Controle',
  'view_controlplanstage': 'Acessar Etapas do Plano de Controle',
  'view_controlplandescription': 'Acessar Descrições do Plano de Controle',

  'view_laiasesmit': 'Acessar Laia',
  'view_riskfactor': 'Acessar Risco',
  'view_laiasesmitdetail': 'Acessar Laia Detail',
  'view_workinstructionlaiadetail': 'Acessar Laia Detail - Workinstruction',
  'view_workinstructionriskfactor': 'Acessar Riscos - Workinstruction',
  'task_audit': 'Auditoria Tarefa',
  'view_home': 'Acessar Página Inicial',
  'view_documenttype': 'Acessar Tipos de Documentos',
  'document_type_documenttype': 'Tipos de Documentos',


  'employee_change_password': 'Acessar Mudança de Senha de Colaboradores',
  'public': 'Público',

  'label-unlimited': 'Ilimitado',
  'report-generate presence list': 'Gerar Lista de presença',
  'msg-evaluation-invalid' : 'Número de tentativas excedido.',
  'title-evaluation-error' : 'Avaliação inválida',
  'label-line-station': 'Linha/Posto',
  'label-line': 'Linha',
  'label-station': 'Posto',
  'label-elaborate': 'Elaborado',
  'label-reviewed-by': 'Revisado por',
  'label-approved-by': 'Aprovado por',
  'label-epi-esd': 'EPI/ESD',
  'label-epi-and-esd': 'EPI\'\s e ESD\'\s',
  'label-select-epi-and-esd': 'Selecione EPI\'s e ESD\'s',
  'label-process': 'Processo',

  'label_flowchart_edit': 'Editar Fluxograma',
  'label-shapes': 'Formas',
  'label-arrows': 'Setas',
  'label-text': 'Texto',
  'label-item-is-not-registered': 'Item não está cadastrado',

  'label-solicitation-homologation': 'Enviar para aprovação no GED',
  'label-height': 'Altura',
  'label-width': 'Largura',
  'label-edit-element': 'Editar Elemento',
  'label-adjust-graph': 'Ajustar página',
  'label-select-the-item': 'Selecione o item',
  'label-amount': 'Quantidade',

  'title-solicitation': 'Solicitação',
  'label-document-type': 'Tipo de documento',
  'label-search-document-type':  'Pesquisar por tipo de documento',
  'title-document-type-add': 'Adicionar Tipo de documento',
  'label-description-type-document': 'Descrição em português',
  'label-description-type-document-en': 'Descrição em inglês',
  'label-document-code': 'Código do Documento',
  'label-document-name': 'Nome do Documento',
  'label-model': 'Modelo do Documento',
  'label-department': 'Departamento',
  'label-scribe': 'Elaborador',
  'label-approver': 'Aprovador',
  'label-homologator': 'Homologador',
  'label-branch': 'Planta',
  'label-document-description': 'Descrição',
  'label-document-version': 'Versão',
  'label-document-date': 'Data',
  'title-document-history' : 'Histórico',
  'label-document-history' : 'Histórico',
  'label-bt-close' : 'Fechar',
  'title-femea' : 'FMEA',
  'label-export' : 'Exportar',

  'label_security_alert': 'Alerta de segurança',
  'label_quality_alert': 'Alerta de qualidade',
  'label_home': 'HOME',
  'title-fmea': 'FMEA',
  'title-nb-fmea': 'Código Fmea',
  'label_step_process': 'Etapas do processo',
  'label_stage_process': 'Fases do processo',
  'label_number_fmea': 'Código do FMEA',
  'label_customer_participant': 'Participante do cliente',
  'title_team_involved': 'Time envolvido',
  'label_selected_item': 'Selecione o item.',
  'label_edit_data': 'Editar dados',
  'label_go_to_FMEA': 'Ir para o FMEA',
  'label-recommended-actions': 'Ações recomendadas *',
  'label-recommended-actions-tool-tip': 'Quais as ações recomendadas para melhorar essa detecção e/ou prevenção?',
  'label-actions-taken-tool-tip': 'Quais foram as ações tomadas e qual o RPN recalculado? incluir a data de conclusão.',
  'label-owner-tool-tip': 'Responsável pela ação.',
  'label-potencial-failure-model-tool-tip': 'De que forma essa entrada principal pode falhar?',
  'label-potencial-failure-effect-tool-tip': 'Qual impacto desse defeito na saída?',
  'label-causes-power-tool-tip': 'Quais as causas que podem levar ao problema nessa entrada principal?',
  'label_current_control-tool-tip': 'Quais os controles/procedimentos existem para evitar que essa falha ocorra?',
  'label-actions-taken': 'Ações tomadas',
  'label-potencial-failure': 'Falha Potencial',
  'label-potencial-failure-mode': 'Modo de falha potencial *',
  'label-potencial-failure-effect': 'Efeito de falha potencial *',
  'label-severity': 'SEV',
  'label-causes-power': 'Causas potenciais *',
  'label-occurrence': 'OCC',
  'label-current-controls': 'Controles atuais',
  'label-detection': 'DET',
  'label-rpn': 'RPN',
  'label-adjusted-rpn': 'RPN Corrigido',
  'label-actions': 'Ações',
  'labe_sequence': 'Sequência',
  'label_add_edit_steps': 'Adicionar/Editar Etapas do processo',
  'label_duplicate': 'Duplicar',
  'label_RPN_low_limit': 'RPN abaixo do limite',
  'label_RPN_above_limit': 'RPN acima do limite',
  'label_delete_actions': 'Excluir Ações',
  'label_current_control': 'Controles atuais',

  'label_recommended_actions': 'Ações recomendadas *',
  'label_actions_taken': 'Ações Tomadas',
  'label_add_failure_mode': 'Adicionar modo de falha',
  'label_edit_failure_mode': 'Editar modo de falha',

  'label_minimal_consent_of_the_client': '1 Consentimento mínimo do cliente',
  'label_some_consent': '2 - 3 Algum consentimento',
  'label_some_dissatisfaction': '4 - 6 Algumas insatisfações',
  'label_high_dissatisfaction': '7 - 8 Altas insatisfações',
  'label_catastrophic': '9 - 10 Catastrófico',

  'label_improvavel': '1 - Improvável',
  'label_little': '2 - 3 Pouca',
  'label_occasionally': '4 - 6 Ocasional',
  'label_repeatedly': '7 - 8 Repetidamente',
  'label_customer_not_satisfied': '9 - 10 Cliente não satisfeito',

  'label_surely_detectable': '1 - 2  Certamente detectável',
  'label_good_chance_of_detection': '3 - 4 Boa chance de detecção',
  'label_maybe_detectable': '5 - 6 Talvez detectável',
  'label_almost_impossible_detect': '7 - 8 Quase não é possível de detectar',
  'label_not_detectable': '9 - 10 Não detectável',

  'label_failure_severity': 'S= Severidade da falha',
  'label_probability_occurrence': 'P= Probabilidade de ocorrência',
  'label_possibility_detection': 'D= Possibilidade de detecção',

  'title-register-biometry': 'Cadastrar Biometria',
  'title-insert-leader-biometry': 'Inserir biometria do líder',
  'label-employee-wait-biometry': 'Aguardando leitura biométrica...',
  'label-employee-recognized-biometry-error': 'Erro ao ler biometria. Tente novamente.',
  'label-employee-recognized-biometry-success': 'Biometria reconhecida com sucesso.',
  'label_wecome': 'Seja bem vindo ao',
  'label_system': 'um sistema da',
  'label_home_access': 'Acesse o menu para mais informações.',

  'label-evaluation-leader-not-valid': 'Biometria do líder inválida. Líder não reconhecido.',
  'ELABORATION'  : 'RASCUNHO',
  'APPROVAL': 'EM REVISÃO',
  'HOMOLOGATION' : 'EM APROVAÇÃO' ,
  'FINALIZED' : 'APROVADO' ,
  'CANCELED' : 'CANCELADO',
  'INVALIDING' : 'EM INVALIDAÇÃO' ,
  'OBSOLETE' : 'ARQUIVADO',
  'DISAPPROVED': 'REPROVADO',
  'REVIEW' : 'EM REVISÃO',
  'REVIEWING' : 'EM REVISÃO',
  'label-email' : 'Email',

  'NO_EMAIL_YOU_USER' : 'É necessário você ter um email cadastrado',
  'NO_USER_EMAIL_APPROVER' : 'É necessário o aprovador ter um email e um usuário cadastrado',
  'NO_USER_EMAIL_HOMOLOGATOR' : 'É necessário o homologador ter um email e um usuário cadastrado',
  'SCRIBE_NOT_FOUND_GED' : 'Você deve ter um usuário com o mesmo email no ged. Entre em contato com administrador do Sistema',
  'APPROVER_NOT_FOUND_GED' : 'O aprovador deve ter um usuário com o mesmo email no ged. Entre em contato com administrador do Sistema',
  'HOMOLOGATOR_NOT_FOUND_GED' : 'O homologador deve ter um usuário com o mesmo email no ged. Entre em contato com administrador do Sistema',

  'close' : 'Fechar',
  'save' : 'Salvar',
  'label-create-copy' : 'Criar cópia',
  'title-document-clone' : 'Criar cópia',
  'exclude_error' : 'Erro ao excluir item. Ele está associado a outro registro',

  'start-evaluation': 'Iniciar Prova',

  'label-pdf': 'Exportar',

  'label-text-box': 'Texto',
  'label-font-size': 'Tamanho da fonte',
  'label-font-color': 'Cor do Texto',
  'label-flowchart-config': 'Configuração do Fluxograma',

  'label-view-new-tab': 'Visualizar em uma nova aba',

  'MGS_CONTAINS_DOCUMENT_COD' : 'Já existe um documento com esse mesmo código. Deseja submeter uma revisão nova?',
  'REQUIRED_DESCRIPTION' : 'Descrição obrigatória',
  'REQUIRED_CODE' : 'Código obrigatório',
  'REQUIRED_CLIENT' : 'Cliente obrigatório',
  'REQUIRED_STAGE_PROCESS' : 'Etapa obrigatória',
  'REQUIRED_STEP_PROCESS' : 'Fase obrigatória',
  'REQUIRED_USER' : 'Usuário do obrigatório',
  'REQUIRED_TEAM_INVOLVED_TWO' : 'São necessarios ao menos duas pessoas envolvidas',
  'REQUIRED_FMEA_ONE_STEP' : 'Fase do FMEA obrigatória',
  'REQUIRED_ONE_STAGE_ON_STEP' : 'Etapa da Fase obrigatória',
  'REQUIRED_POTENTIAL_FAILURE_ON_STAGE' : 'Falha Potencial do Etapa obrigatório',
  'REQUIRED_POTENTIAL_FAILURE_MODES' : 'Falha Potencial obrigatório',
  'REQUIRED_POTENTIAL_FAILURE_EFFECTS' : 'Efeitos da Falha Potencial obrigatório',
  'REQUIRED_POTENTIAL_FAILURE_SEVERITY' : 'Severidade da Falha Potencial obrigatório',
  'REQUIRED_POTENTIAL_FAILURE_CAUSES' : 'Causas da Falha Potencial obrigatório',
  'REQUIRED_POTENTIAL_FAILURE_OCCURRENCE' : 'Ocorrência da Falha Potencial obrigatório',
  'REQUIRED_POTENTIAL_FAILURE_DETECTION' : 'Detecção da Falha Potencial obrigatório',
  'REQUIRED_RPN_REF' : 'RPN Padrão obrigatório',
  'label-add-fmea': 'Adicionar Dados do FMEA',

  'title-file-version' : 'Solicitação',
  'title-type' : 'Tipo',
  'title-author' : 'Autor',
    'Identification Label' : 'Etiqueta de Identificação',
    'Standard Work Instruction' : 'Instrução de Trabalho Padrão',
    'Operational Work Instruction	' : 'Instrução de Trabalho Operacional',
    'Master List' : 'Lista Mestra',
    'Standard Operating Procedure' : 'Procedimento Operacional Padrão',
    'Operational Register' : 'Registro Operacional',
    'Management System Manual' : 'Manual do Sistema de Gestão',
    'Standard Forms		' : 'Formulários Padrões',
    'Failure Mode and Effects Analysis ' : 'Análise de Modos de Falhas e Efeitos',
    'Polyci' : 'Políticas',
    'Process Mapping' : 'Mapeamento de Processo',
    'Engineering Change' : 'Mudanças de Engenharia',
    'External Documents' : 'Documentos Externos',
  'label_prazo': 'Prazo',
  'label_title_docs': 'Submissão de documentos',
  'label_type_docs': 'Tipo de documento',
  'label_code_docs': 'Código do documento',
  'label_arquivo_pdf': 'Selecionar arquivo PDF *',
  'label_arquivo_editavel': 'Selecionar arquivo editável *',
  'label_interessed': 'Partes interessadas',
  'title-ged': 'GED',
  'title-file-version-task' : 'Tarefas Pendentes',
  'title-deadline': 'Data limite',
  'label-download': 'Download',
  'label-approve': 'Aprovar',
  'label-desapprove': 'Reprovar',
  'label-confirm-remove-file': 'Deseja remover o arquivo?',
  'label-send-approval': 'Enviar para Revisão',
  'label-send-homogate': 'Enviar para Aprovação',
  'label-homologate': 'Aprovar',
  'label-new-process': 'Reiniciar Processo',
  'label-request-review': 'Solicitar Revisão',
  'title-current-document' : 'Documentos Vigentes',
  'title-drawing-up-documents' : 'Elaboração de documentos',
  'title-add-document': 'Adicionar documento',
  'title-edit-document': 'Editar documento',
  'add_folder' : 'Adicionar Pasta',
  'rename_folder' : 'Renomear Pasta',
  'detail' : 'Detalhe',
  'importing' : 'Importando',
  'importing-production-lines' : 'Importando linhas de produção',
  'current_documents': 'Documentos Vigentes',
  'label_local': 'Local de destino',
  'label_select': 'Selecionar',
  'label_reviewer': 'Revisor',
  'label-move': 'Mover',
  'task-expired': 'Tarefa Expirada',
  'file_editable' : 'Arquivo Editável',
  'file_pdf' : 'Arquivo PDF',
  'select_destination_of_file' : 'Selecione o Local de destino.',
  'required_field' : 'Campo obrigatório',
  'label_editable': 'Editável',
  'label_file_editable': 'Arquivo editável',
  'label_latest_version': 'Última versão',
  'label-search': 'Pesquisar',
  'label-search-by-code': 'Pesquisar por Código',
  'label-search-by-name': 'Pesquisar por Nome',
  'select_folder' : 'Selecionar Pasta',
  'local' : 'Local',
  'label-reprove-justification': 'Justificativa da reprovação',
  'placeholder-justification': 'Justificativa',
  'VALID_EMAIL': 'email inválido',
  'toast-block-delete': 'Existe uma Questão associada a esta avaliação.',
  'label_permission_allocated': 'Permissões atribuídas',
  'label_title_solicitation': 'Submissões de documentos',
  'already-exists-login' : 'Login já existe',
  'label-subscriber': 'Elaborador',
  'label-request-revision' : 'Solicitar Revisão',
  'obsolte_documents' : 'Documentos Arquivados',
  'label-invalidate-document' : 'Invalidar',
  'label-request-invalidation' : 'Solicitar Invalidação',
  'label-confirm-invalidate-document' : 'Você realmente quer invalidar este item?',
  'label-min-number-characters' : 'Número mínimo de caracteres',
  'label-existing-doc' : 'Doc. Existente',
  'label-last-revision': 'Última Revisão',
  'label-file-formart': 'Formato do Arquivo',
  'label-revision': 'Revisão',
  'label-open': 'Abrir Pasta',
  'label-recover': 'Recuperar',
  'label-folder': 'Pasta',
  'label-search-production-line': 'Pesquisar por Linha de Produção',
  'TRAINED': 'Colaborador treinado',
  'WITHOUT_TRAINING': 'Colaborador sem treinamento',
  'LOGGED_OFF': 'Colaborador deslogado',
  'IN_TRAINING': 'Colaborador em treinamento',
  'title-setting-tracking-dialog': 'Configurações do Painel',
  'title-setting-tracking-dialog-sub': 'Tempo e Visualização de Linhas',
  'label-time-swap': 'Tempo',
  'link' : 'Link',
  'label-branch-search': ' Pesquisa por Planta',
  'title-branch': 'Planta',
  'label-deallocate': 'Desalocar',
  'label-reallocate': 'Realocar',
  'label-justification': 'Jusficativa',
  'report_workstation': 'Histórico de Posto de trabalho / Colaborador',
  'REQUIRED_MODELS' : 'É necessário algum modelo associado a Instrução de trabalho',

  'documents' : 'Documentos',
  'document_name' : 'Nome do Documento',
  'description_version' : 'Motivo da submissão',
  'required_interested_parts' : 'Necessário parte interessadas',
  'document-details': 'Detalhes do documento',
  'label-delete-all': 'Excluir todos',
  'label-delete-select': 'Excluir selecionados',
  'report_report_rotation': 'Gerar Lista de Revezamento',
  'document-type': 'Tipo de Documento',
  'required_profiles' : 'Perfil é obrigatório.',
  'approver_file'  :	'Pode aprovar arquivos',
  'homologator_file'  :	'Pode homologar arquivos',
  'scribe_file'  :	'Pode gravar arquivos',
  'adm_file'  :	'Pode administrar arquivos',
  'view_editable_file'  :	'Pode ver arquivos editáveis',
  'REQUIRED_EDITABLE_FILE' : 'Required the editable file.',
  'REQUIRED_PDF_FILE' : 'Required the pdf file.',

  'REQUIRED_MATERIAL_TOOLS' : 'É necessário selecionar os Materiais e Ferramentas na Instrução de Trabalho.',
  'REQUIRED_NAME' : 'É necessário preencher o nome.',
  'REQUIRED_PROCESS_PHASE' : 'É necessário selecionar Fase do Processo na Instrução de Trabalho.',
  'REQUIRED_DESCRIPTION_NOTES' : 'É necessário preencher o Alerta de Segurança na Instrução de Trabalho.',
  'REQUIRED_STEPS' : 'É necessário informar os passos na Instrução de Trabalho.',
  'REQUIRED_STEPS_SESMT' : 'É necessário informar os passos do SESMT na Instrução de Trabalho.',
  'REQUIRED_RISK' : 'É necessário informar os Riscos.',
  'REQUIRED_LAIA' : 'É necessário preencher LAIA.',
  'label_save_caster': 'Salvar rodízio',
  'label_add_group': 'Adicionar grupo',
  'label_group': 'Grupo',
  'label-automatic-rotation': 'Rotação automática',
  'label-confirm-stop-caster': 'Deseja finalizar o rodízio automático?\n' + 'Todos os colaboradores será desalocados de seus Posto.',

  'title-department-add': 'Adicionar Departamento',
  'title-department': 'Departamento',
  'title-go-fmea': 'Ir para o Fmea',
  'evaluation-associated': 'Existe uma avaliação associada a esta IT.',
  'not-selected' : 'Não selecionado',
  'redirect-title': 'Redirecionamento',
  'unsigned-user' : 'Tarefa não assinaada para esse usuário',
  'task-finalized-user' : 'Tarefa finalizada. Para conferir faça o login novamente..',

  'title-risk-factor': 'Fatores de risco',
  'PHYSICAL_RISK': 'Físico',
  'BIOLOGICAL_RISK': 'Biológico',
  'CHEMICAL_RISK': 'Químico',
  'others_RISK': 'Outros',
  'ERGONOMIC_RISK': 'Ergonômico',
  'ACCIDENTS_RISK': 'Acidente',
  'label-risk-code-search': 'Código',
  'label-risk-description-search': 'Descrição',
  'label-risk-version-search': 'Versão',
  'label-risk-type-search': 'Tipo',
  'ALL_TYPES': 'Todos os tipos',
  'title-risk-factor-add': 'Adicionar Fator de Risco',
  'label-risk-description': 'Descrição',
  'label-risk-version': 'Versão',
  'label-risk-code': 'Código',
  'label-risk-type': 'Tipo',
  'label-current-version': 'Versão Atual',
  'label-work-instruction-instructions-list-code': 'Código IT',

  'label__add_decription': 'Adicionar descrição e Tipo',
  'label_aspects': 'Aspectos Ambientais',
  'label_impacts': 'Impactos Ambientais',
  'label_control': 'Controle Operacional',
  'label_classification': 'Classificação',
  'label_type_laia': 'Tipos',
  'label_laia_combination': 'Assosiar LAIA',
  'label_laia': 'Associação LAIA',
  'label_create_laia': 'Cadastro LAIA',

  'label_description_risk': 'Descrição',
  'label_version_risk': 'Versão',
  'label_code_risk': 'Código',
  'label_type_risk': 'Tipo',
  'label_list_risk': 'Fatores de riscos',
  'label-control-measure': 'Medida de Controle',
  'title-register-signature': 'Cadastrar assinatura',
  'clear': 'Limpar',
  'signature' : 'Assinatura',

  'label-material-image': 'Imagem do Material',

  'label-register-search': 'Pesquisar por Matrícula',
  'label-resolved-checked': 'Resolver sugestões marcadas',
  'title-homologated-at' : 'Data de Homologação',
  'title-control-plan' : 'Plano de Controle',
  'label-code-control-plan' : 'Código Plano de Controle',
  'label-type-control-plan' : 'Tipo',
  'label-client-control-plan' : 'Cliente',
  'label-engineering-client-control-plan' : 'Engenharia do Cliente',
  'label-model-control-plan' : 'Modelo',
  'label-dt-create-control-plan' : 'Data Criação',
  'label-situation-control-plan' : 'Situação',
  'label-version-control-plan' : 'Versão',
  'label-serial-number-control-plan' : 'Número de série/Último Nível de Mudança',
  'label-provider-control-plan' : 'Fornecedor',
  'label-provider-outher-control-plan' : 'Outras aprovações Fornecedor',
  'label-fmea-plan' : 'Ref. & FMEA Número',
  'label-client-plan' : 'Cliente',
  'label-others-client-plan' : 'Outras Aprovações Cliente',
  'label-contact-plan' : 'Contato',
  'label-search-code-control-plan' : 'Pesquisar por Código',
  'label-search-model-control-plan' : 'Pesquisar por Modelo',
  'label-search-situation-control-plan' : 'Pesquisar por Situação',
  'label-search-date-init-control-plan' : 'Data Inicial',
  'label-search-date-end-control-plan' : 'Data Final',
  'label-approval': 'Aprovações',
  'label-team': 'Equipe',
  'label-name-team': 'Nome',
  'label-deparment-team': 'Setor',
  'label-cpf': 'CPF',
  'label-admission-date': 'Data de Admissão',
  'label-birth-date': 'Data de Nascimento',
  'label-employee-situation': 'Situação do Empregado',
  'label-leadership-id': 'ID Chefia',
  'label-shift': 'Turma',
  'label-occupation': 'Cargo',




  'quiz-audit' : 'Formulário de Auditoria',
  'questions' : 'Perguntas',
  'question-add': 'Adicionar Perguntas',

  'audit' : 'Auditoria',
  'result' : 'Resultado',
  'model' : 'Modelo',
  'work-instruction' : 'I.T',
  'status' : 'Status',
  'validity' : 'Validade',
  'implementation' : 'Implementação',
  'cycle' : 'Ciclo',
  'responsible' : 'Responsável',
  'auditor' : 'Auditor',
  'ACCORDANCE' : 'C',
  'NOT_IN_ACCORDANCE' : 'NC',
  'AUDIT_PENDING' : 'Pend',
  'AUDIT_WAITING_ACTIONS' : 'Aguardando Ações',
  'AUDIT_WAITING_VALIDATION' : 'Aguardando Validações',
  'AUDIT_DONE' : 'OK',
  'additional_data' : 'Dados adicionais',
  'AUDIT_NEW' : 'Nova',
  'AUDIT_STARTED' : 'Iniciada',
  'shift' : 'Turno',
  'area' : 'Área',
  'bt-accordance' : 'Conforme',
  'bt-not-accordance' : 'Não conforme',
  'start-audit' : 'Fazer auditoria',
  'not-accordance-description' : 'Descrição de não conformidade',
  'questions-dialog-audit' : 'É necessário  responder todas as questões.',
  'questions-dialog-audit-accordance' : 'Auditoria concluída com sucesso. Após finalizar não será possivel editar.',
  'questions-dialog-audit-not-accordance' : 'Auditoria concluída, existem itens não conformes,  após finalizar o responsável deverá preencher: Causa Raíz, Acão Imediata e Ação Corretiva.',
  'questions-dialog-audit-not-accordance-action' : 'Salvo com sucesso, existem ações corretivas. O Auditor precisa validá-las e incluir Evidência da eficácia.',
  'questions-dialog-audit-not-accordance-done' : 'Auditoria concluída com sucesso. Após finalizar não será possivel editar.',
  'questions-dialog-audit-done' : 'Auditoria já está concluída e não pode ser mais editada',
  'required_audit_field_actions':'É necessário prencher: Causa Raíz, Acão Imediata e Ação Corretiva.',
  'required_audit_field_validate':'É necessário validar e incluir Evidência da eficácia.',
  'root_cause' : 'Causa Raíz',
  'immediate_action' : 'Ação Imediata',
  'corrective_action' : 'Ação Corretiva',
  'evidence_of_effficacy' : 'Evidência da eficácia',

  'title-evidence_of_effficacy' : 'Evidência da eficácia',
  'the_actions_effective' : 'As ações foram eficazes?',
  'INCOMPLETE_FIELDS': 'Campos incompletos',
  'LABEL_CONTROL_PLAN_MACHINE': 'Máquina, dispositivo, jig, ferramenta para Manufatura',
  'LABEL_CONTROL_PLAN_PRODUCT': 'Produto, Processo especificação, Tolerancia',
  'LABEL_CONTROL_PLAN_MEASUREMENT': 'Medição de avaliação técnica',
  'LABEL_CONTROL_PLAN_METHOD': 'Método de controle',
  'LABEL_CONTROL_PLAN_ACTION': 'Plano de Reação',
  'LABEL_SIZE': 'Tamanho',
  'LABEL_FREQUENCY': 'Frequência',
  'LABEL_FEATURE': 'Características',
  'LABEL_METHOD': 'Método',
  'confirm_current' : 'Você quer mudar para atual?',
  'host' : 'Host',
  'port' : 'Porta',
  'username' : 'Usuário',
  'from_email' : 'Remetente',
  'fail_silently' : 'Silenciar Falha',
  'use_tls' : 'Usar TLS',

  'current' : 'Atual',
  'email-config' : 'Email Configuração',
  'bt-send-mail-test' : 'Enviar email de teste',
  'email_to' : 'Para',
  'data' : 'Dados',
  'version' : 'Versão',
  'required_user_employee' : 'O responsável deve ter  usuário com login e senha',
  'audit-task' :'Tarefas de Auditoria',
  'QUIZ_AUDIT_NOT_CONTAINS_QUESTIONS': 'Formulário de auditoria não possui perguntas',
  'copy_control_plan': 'Duplicar Control Plan',
  'CONFIRM_ADD_BIOMETRY': 'Deseja cadastrar biometria?',
  'label-step-fmea': 'Entradas Principais',
  'label-stage-fmea': 'Etapas do Processo',
  'label-export-xls-control-plan': 'Exportar XLSX',
  'check_status_on_ged':'Verificar situação no GED',
  'document_not_found_on_ged' : 'Documento não encontrado no GED',
  'processing' :'Processando...',
  'msg-fmea-alter': 'FMEA de referência foi alterado, todos os cards (Etapas e Processo) seram alterados e detalhes perdidos, Deseja continuar?',
  'labe-alter-cpf' : 'Alterar Informações',
  'labe-cpf' : 'CPF',
  'cannot-deleted-user-create' : 'Colaborador não pode ser excluido pois possui login criado',
  'cannot-deleted-employee-alocate' : 'Colaborador não pode ser excluido pois possui está alocado em um posto',
  'audit_not_accordance' : 'Não conforme',
  'audit_accordance' : 'Conforme',
  'audit_new' : 'Nova',
  'audit_started' : 'Iniciada',
  'save_image' : 'Salvar Imagem',
  'audits_without_actions':'Auditorias sem Ações',
  'audit-area-not-accordance' : 'Não conformidade por Área',
  'audit-model-not-accordance' : 'Não conformidade por Modelo - Área:',
  'fmea_vs_controlplan': 'FMEA x Plano de Controle',
  'without_control_plan': 'FMEA Sem Plano de Controle',
  'with_control_plan': 'FMEA Com Plano de Controle',
  'no_user' : 'Sem login cadastrado',
  'pedding' : 'Pendente',
  'done' : 'Concluído',
  'evaluation_pedding': 'Treinamentos Pendentes',
  'view-img': 'Visualização',
  'reproveed' : 'Reprovado' ,
  'label-spot-error': 'Erro ao salvar ponto de acesso. Tente novamente.',
  'label-load-workstations-error': 'Erro ao carregar postos de trabalho.',
  'label-color': 'Cor',
  'title-plant-view': 'Planta',
  'label-qty_evaluation' : 'Qtd de Treinamentos',
  'evaluation-not-performed' : 'Avaliação Pendente',
  'area-all': 'Todas as áreas',
  'connect-erro-to-ged': 'Erro ao conectar no GEDWEB',
  'label-process-flow-preview': 'Visualizar',
  'material-it-subtitle': '* Somente cinco Materiais serão mostrados na exportação da IT',
  'model-it-subtitle': '* Somente três Modelos serão mostrados na exportação da IT',
  'The fields quizAudit, statement must make a unique set.' : 'Pergunta já existe.',
  'workstation-production-line-exist' : 'Posto de trabalho já cadastrado na planta',
  'The fields name must make a unique set.': 'Item já está cadastrado.',
  'send-to-ged' : 'Enviar para GED',
  'start_date': 'Data de inicio',
  'label-bt-exit': 'Sair',
  'color-picker': 'Selecionar cor',
  'view_plantpoints': 'Pontos Planta',
  'view_plantview': 'Planta',
  'APPROVER_EMAIL_ERROR': 'Email do aprovador não encontrado',
  'HOMOLOGATOR_EMAIL_ERROR': 'Email do homologador não encontrado'

};

